force-app/main/default/objects/Container__c/Container__c.object-meta.xml
<CustomObject>
    <label>Container</label>
    <nameField>
        <label>Container Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Containers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Container__c/fields/Issuance_Date__c.field-meta.xml
<CustomField>
    <fullName>Issuance_Date__c</fullName>
    <label>Issuance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Container__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Arrived for issuance</fullName>
            </value>
            <value>
                <fullName>Arrived for shipment</fullName>
            </value>
            <value>
                <fullName>Awaiting issuance</fullName>
            </value>
            <value>
                <fullName>Awaiting shipment</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Выдан</fullName>
                <isActive>false</isActive>
                <label>Выдан</label>
            </value>
            <value>
                <fullName>Ожидает выдачи</fullName>
                <isActive>false</isActive>
                <label>Ожидает выдачи</label>
            </value>
            <value>
                <fullName>Ожидает отгрузки</fullName>
                <isActive>false</isActive>
                <label>Ожидает отгрузки</label>
            </value>
            <value>
                <fullName>Прибыл для выдачи</fullName>
                <isActive>false</isActive>
                <label>Прибыл для выдачи</label>
            </value>
            <value>
                <fullName>Прибыл на отгрузку</fullName>
                <isActive>false</isActive>
                <label>Прибыл на отгрузку</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Container__c/fields/Warehouse_Cell__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Cell__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse Cell</label>
    <referenceTo>Cell__c</referenceTo>
    <relationshipLabel>Containers</relationshipLabel>
    <relationshipName>Containers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Container_Warehouse__c/Container_Warehouse__c.object-meta.xml
<CustomObject>
    <label>Container Warehouse</label>
    <nameField>
        <label>Container Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Container Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Container_Warehouse__c/fields/Length__c.field-meta.xml
<CustomField>
    <fullName>Length__c</fullName>
    <description>Container count</description>
    <label>Length</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Container_Warehouse__c/fields/Max_Cell_Level__c.field-meta.xml
<CustomField>
    <fullName>Max_Cell_Level__c</fullName>
    <description>Container count</description>
    <label>Max Cell Level</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Container_Warehouse__c/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <description>Container count</description>
    <label>Width</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Warehouse_Cell__c/Warehouse_Cell__c.object-meta.xml
<CustomObject>
    <label>Warehouse Cell</label>
    <nameField>
        <label>Warehouse Cell Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouse Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse_Cell__c/fields/Container_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Container_Warehouse__c</fullName>
    <label>Container Warehouse</label>
    <referenceTo>Container_Warehouse__c</referenceTo>
    <relationshipLabel>Warehouse Cells</relationshipLabel>
    <relationshipName>Warehouse_Cells</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/WarehouseController.cls
/**
 * @description  WarehouseController.
 * @author Kostiantyn Murin
 * @date 07-07-2023
 */
public with sharing class WarehouseController {

    /**
     * @description  getWarehouseStructure.
     * @author Kostiantyn Murin
     * @date 07-07-2023
     * @param recordId warehouse Id
     * @return Map<String, Object>
     */
    @AuraEnabled
    public static Map<String, Object> getWarehouseStructure(String recordId) {
        try {
            Container_Warehouse__c warehouse = [SELECT Id,
                                                       Length__c,
                                                       Width__c,
                                                       Max_Cell_Level__c
                                                FROM Container_Warehouse__c
                                                WHERE Id = :recordId];
            ContainerWarehouseStructure structure = new ContainerWarehouseStructure(warehouse);
            return new Map<String, Object>{
                'isSuccess' => true,
                'responseObj' => new Map<String, Object>{
                                    'matrix' => structure.getWarehouseMatrix(),
                                    'warehouseWidth' => structure.getWidth(),
                                    'warehouseLength' => structure.getLength()
                                }
            };
        } catch (Exception e) {
            return new Map<String, Object>{
                'isSuccess' => false,
                'responseObj' => null,
                'message' => e.getMessage()
            };
        }
    }

    /**
     * @description  getUnlocatedContainerList.
     * @author Kostiantyn Murin
     * @date 07-07-2023
     * @return Map<String, Object>
     */
    @AuraEnabled
    public static Map<String, Object> getUnlocatedContainerList(){
        try {
            List<Container__c> unlocatedContainerList = [SELECT Id,
                                                                Issuance_Date__c,
                                                                Status__c
                                                         FROM Container__c
                                                         WHERE Warehouse_Cell__c = NULL
                                                         AND Status__c != 'Issued'
                                                         ORDER BY Issuance_Date__c DESC];
        return new Map<String, Object>{
            'isSuccess' => true,
            'responseObj' => unlocatedContainerList
        };
            
        } catch (Exception e) {
            return new Map<String, Object>{
                'isSuccess' => false,
                'responseObj' => null,
                'message' => e.getMessage()
            };
        }
    }
}