force-app/main/default/objects/Container__c/Container__c.object-meta.xml
<CustomObject>
    <label>Container</label>
    <nameField>
        <label>Container Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Containers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Container__c/fields/Issuance_Date__c.field-meta.xml
<CustomField>
    <fullName>Issuance_Date__c</fullName>
    <label>Issuance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Container__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Arrived for issuance</fullName>
            </value>
            <value>
                <fullName>Arrived for shipment</fullName>
            </value>
            <value>
                <fullName>Awaiting issuance</fullName>
            </value>
            <value>
                <fullName>Awaiting shipment</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Выдан</fullName>
                <isActive>false</isActive>
                <label>Выдан</label>
            </value>
            <value>
                <fullName>Ожидает выдачи</fullName>
                <isActive>false</isActive>
                <label>Ожидает выдачи</label>
            </value>
            <value>
                <fullName>Ожидает отгрузки</fullName>
                <isActive>false</isActive>
                <label>Ожидает отгрузки</label>
            </value>
            <value>
                <fullName>Прибыл для выдачи</fullName>
                <isActive>false</isActive>
                <label>Прибыл для выдачи</label>
            </value>
            <value>
                <fullName>Прибыл на отгрузку</fullName>
                <isActive>false</isActive>
                <label>Прибыл на отгрузку</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Container__c/fields/Warehouse_Cell__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Cell__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse Cell</label>
    <referenceTo>Cell__c</referenceTo>
    <relationshipLabel>Containers</relationshipLabel>
    <relationshipName>Containers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Container_Warehouse__c/Container_Warehouse__c.object-meta.xml
<CustomObject>
    <label>Container Warehouse</label>
    <nameField>
        <label>Container Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Container Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse_Cell__c/Warehouse_Cell__c.object-meta.xml
<CustomObject>
    <label>Warehouse Cell</label>
    <nameField>
        <label>Warehouse Cell Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouse Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse_Cell__c/fields/Container_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Container_Warehouse__c</fullName>
    <label>Container Warehouse</label>
    <referenceTo>Container_Warehouse__c</referenceTo>
    <relationshipLabel>Warehouse Cells</relationshipLabel>
    <relationshipName>Warehouse_Cells</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Warehouse_Cell__c/fields/Is_Empty__c.field-meta.xml
<CustomField>
    <fullName>Is_Empty__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Empty</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/WarehouseCellTriggerHandler.cls
/**
 * @description  Trigger handler for the Warehouse_Cell__c object.
 * @author Kostiantyn Murin
 * @date 18-06-2023
 */
public with sharing class WarehouseCellTriggerHandler implements ITriggerHandler {
    private static final List<String> ARRIVED_STATUSES_LIST = new List<String>{ 'Arrived for issuance', 'Arrived for shipment' };
    /**
     * @description   Before insertion helper method
     * @author Kostiantyn Murin
     * @date 18-06-2023
     * @param newList List<SObject>
     */
    public void beforeInsert(List<SObject> newList) {}

    /**
     * @description   Before updation helper method
     * @author Kostiantyn Murin
     * @date 18-06-2023
     * @param newMap Map<Id, SObject> newMap
     * @param oldMap Map<Id, SObject> newMap
     */
    public void beforeUpdate(Map<Id, SObject> newMap, Map<Id, SObject> oldMap) {}

    /**
     * @description   Before deletion helper method
     * @author Kostiantyn Murin
     * @date 18-06-2023
     * @param oldMap Map<Id, SObject> newMap
     */
    public void beforeDelete(Map<Id, SObject> oldMap) {}

    /**
     * @description   After insertion helper method
     * @author Kostiantyn Murin
     * @date 18-06-2023
     * @param newMap Map<Id, SObject> newMap
     */
    public void afterInsert(Map<Id, SObject> newMap) {}

    /**
     * @description   After updation helper method
     * @author Kostiantyn Murin
     * @date 18-06-2023
     * @param newMap Map<Id, SObject> newMap
     * @param oldMap Map<Id, SObject> newMap
     */
    public void afterUpdate(Map<Id, SObject> newMap, Map<Id, SObject> oldMap) {
        moveContainersFromTemporaryStorage(newMap.values(), oldMap);
        publishPlatformEvent(newMap.values());
    }

    /**
     * @description   After deletion helper method
     * @author Kostiantyn Murin
     * @date 18-06-2023
     * @param oldMap Map<Id, SObject> newMap
     */
    public void afterDelete(Map<Id, SObject> oldMap) {}

    /**
     * @description   After undeletion helper method
     * @author Kostiantyn Murin
     * @date 18-06-2023
     * @param newMap Map<Id, SObject> newMap
     * @param oldMap Map<Id, SObject> newMap
     */
    public void afterUndelete(Map<Id, SObject> oldMap) {}

    private static void moveContainersFromTemporaryStorage(List<Warehouse_Cell__c> newList, Map<Id, SObject> oldMap) {
        Boolean isCellEmpty = false;
        for (Warehouse_Cell__c cell : newList) {
            Warehouse_Cell__c oldCell = (Warehouse_Cell__c)oldMap.get(cell.Id);
            if (cell.Is_Empty__c && !oldCell.Is_Empty__c) {
                isCellEmpty = true;
                break;
            }
        }
        if (!isCellEmpty) {
            return;
        }
        List<Container__c> containerList = [
            SELECT Id, Issuance_Date__c, Status__c
            FROM Container__c
            WHERE Status__c IN :ARRIVED_STATUSES_LIST
            AND Warehouse_Cell__c = null
            ORDER BY Issuance_Date__c DESC
        ];
        if (!containerList.isEmpty()) {
            ContainerDistributorBatch distributorBatch = new ContainerDistributorBatch(containerList);
            Database.executeBatch(distributorBatch, 200);
        }
    }

    private void publishPlatformEvent(List<Warehouse_Cell__c> newList) {
        Set<Id> warehouseIdSet = new Set<Id>();
        for (Warehouse_Cell__c cell : newList) {
            warehouseIdSet.add(cell.Container_Warehouse__c);
        }
        PlatformEventBuilder.publishContainerWarehouseUpdateEvent(warehouseIdSet);
        PlatformEventBuilder.publishUnlocatedContainersCreatedEvent(warehouseIdSet);
    }
}