force-app/main/default/objects/Container__c/Container__c.object-meta.xml
<CustomObject>
    <label>Container</label>
    <nameField>
        <label>Container Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Containers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Container__c/fields/Issuance_Date__c.field-meta.xml
<CustomField>
    <fullName>Issuance_Date__c</fullName>
    <label>Issuance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Container__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Arrived for issuance</fullName>
            </value>
            <value>
                <fullName>Arrived for shipment</fullName>
            </value>
            <value>
                <fullName>Awaiting issuance</fullName>
            </value>
            <value>
                <fullName>Awaiting shipment</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Выдан</fullName>
                <isActive>false</isActive>
                <label>Выдан</label>
            </value>
            <value>
                <fullName>Ожидает выдачи</fullName>
                <isActive>false</isActive>
                <label>Ожидает выдачи</label>
            </value>
            <value>
                <fullName>Ожидает отгрузки</fullName>
                <isActive>false</isActive>
                <label>Ожидает отгрузки</label>
            </value>
            <value>
                <fullName>Прибыл для выдачи</fullName>
                <isActive>false</isActive>
                <label>Прибыл для выдачи</label>
            </value>
            <value>
                <fullName>Прибыл на отгрузку</fullName>
                <isActive>false</isActive>
                <label>Прибыл на отгрузку</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Container__c/fields/Warehouse_Cell__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Cell__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse Cell</label>
    <referenceTo>Cell__c</referenceTo>
    <relationshipLabel>Containers</relationshipLabel>
    <relationshipName>Containers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Container_Warehouse__c/Container_Warehouse__c.object-meta.xml
<CustomObject>
    <label>Container Warehouse</label>
    <nameField>
        <label>Container Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Container Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse_Cell__c/Warehouse_Cell__c.object-meta.xml
<CustomObject>
    <label>Warehouse Cell</label>
    <nameField>
        <label>Warehouse Cell Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouse Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse_Cell__c/fields/Container_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Container_Warehouse__c</fullName>
    <label>Container Warehouse</label>
    <referenceTo>Container_Warehouse__c</referenceTo>
    <relationshipLabel>Warehouse Cells</relationshipLabel>
    <relationshipName>Warehouse_Cells</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ContainerDistributorBatch.cls
/**
 * @description  The batch class for distribute containers.
 * @author Kostiantyn Murin
 * @date 07-07-2023
 */
public with sharing class ContainerDistributorBatch implements Database.Batchable<Container__c>, Database.Stateful {

    private List<Container__c> containerList;
    private String issuedStatus = 'Issued';
    private String query = 'SELECT Id, ' +
                          '        Issuance_Date__c, ' +
                          '        Status__c ' +
                          'FROM Container__c ' +
                          'WHERE Warehouse_Cell__c = null ' +
                          'AND Status__c != :issuedStatus ' +
                          'AND Issuance_Date__c != null ' +
                          'ORDER BY Issuance_Date__c DESC';

    /**
     * @description  Constructor.
     * @author Kostiantyn Murin
     * @date 07-07-2023
     */
    public ContainerDistributorBatch(List<Container__c> containerList) {
        this.containerList = containerList;
    }

    /**
     * @description  Constructor.
     * @author Kostiantyn Murin
     * @date 07-07-2023
     */
    public ContainerDistributorBatch() {}
    
    /**
     * @description  Collect the batches of records or objects to be passed to execute. Container__c list.
     * @author Kostiantyn Murin
     * @date 07-07-2023
     */
    public Iterable<Container__c> start(Database.BatchableContext BC) {
        if (containerList == null) {
            System.Iterable<Container__c>  contList = (Iterable<Container__c>)Database.getQueryLocator(this.query);
            return contList;
        }
        return (Iterable<Container__c>)this.containerList;
    }

    /**
     * @description  Process each batch of Container__c records. Run ContainerDistributorService
     * @author Kostiantyn Murin
     * @date 07-07-2023
     */
    public void execute(Database.BatchableContext BC, List<Container__c> scope){
        ContainerDistributorService service = new ContainerDistributorService(scope);
        service.run();
    }

    /**
     * @description  Publish platform Event
     * @author Kostiantyn Murin
     * @date 07-07-2023
     */
    public void finish(Database.BatchableContext BC){
        publishPlatformEvent();
    }

    private static void publishPlatformEvent() {
        Map<Id, Container_Warehouse__c> warehouseMap = new Map<Id, Container_Warehouse__c>([
                SELECT Id FROM Container_Warehouse__c
            ]);
        PlatformEventBuilder.publishUnlocatedContainersCreatedEvent(warehouseMap.keySet());
    }
}