force-app/main/default/objects/Container__c/Container__c.object-meta.xml
<CustomObject>
    <label>Container</label>
    <nameField>
        <label>Container Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Containers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Container__c/fields/Contact_Ext_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Ext_Id__c</fullName>
    <label>Contact Ext Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContainerTRDispatcher.cls
public with sharing class ContainerTRDispatcher {
    
    public static void populateValuesOnArrival(List<Container__c> processingRecords) {
        System.debug('ContainerTRDispatcher => populateValuesOnArrival');

        ContainerTRService.populateValuesOnArrival(processingRecords);
    }

    public static void assignContacts(List<Container__c> processingRecords) {
        System.debug('ContainerTRDispatcher => assignContacts');

        Set<String> contactsExternalIds = new Set<String>();
        List<Container__c> containersToLinkContacts = new List<Container__c>();

        for (Container__c container_i : processingRecords) {
            
            if (String.isBlank(container_i.Contact_Ext_Id__c)) {
                continue;
            }
            
            contactsExternalIds.add(container_i.Contact_Ext_Id__c);
            containersToLinkContacts.add(container_i);
        }

        if (containersToLinkContacts.isEmpty()) {
            return;
        }

        ContainerTRService.assignContacts(containersToLinkContacts, contactsExternalIds);
    }

    public static void scheduleContactAssignmentJob() {

        List<CronTrigger> existedJobs = [
            SELECT Id
            FROM CronTrigger
            WHERE CronJobDetail.Name = 'ContactsCreationBatch'
            AND State != 'COMPLETE'
        ];

        if (!existedJobs.isEmpty()) {
            return;
        }

        ContainerTRService.scheduleContactAssignmentJob();
    }
}