force-app/main/default/objects/Container__c/Container__c.object-meta.xml
<CustomObject>
    <label>Container</label>
    <nameField>
        <label>Container Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Containers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Container__c/fields/Issuance_Date__c.field-meta.xml
<CustomField>
    <fullName>Issuance_Date__c</fullName>
    <label>Issuance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Container__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Arrived for issuance</fullName>
            </value>
            <value>
                <fullName>Arrived for shipment</fullName>
            </value>
            <value>
                <fullName>Awaiting issuance</fullName>
            </value>
            <value>
                <fullName>Awaiting shipment</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Выдан</fullName>
                <isActive>false</isActive>
                <label>Выдан</label>
            </value>
            <value>
                <fullName>Ожидает выдачи</fullName>
                <isActive>false</isActive>
                <label>Ожидает выдачи</label>
            </value>
            <value>
                <fullName>Ожидает отгрузки</fullName>
                <isActive>false</isActive>
                <label>Ожидает отгрузки</label>
            </value>
            <value>
                <fullName>Прибыл для выдачи</fullName>
                <isActive>false</isActive>
                <label>Прибыл для выдачи</label>
            </value>
            <value>
                <fullName>Прибыл на отгрузку</fullName>
                <isActive>false</isActive>
                <label>Прибыл на отгрузку</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Container__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Containers</relationshipLabel>
    <relationshipName>Containers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Container__c/fields/Warehouse_Cell__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Cell__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse Cell</label>
    <referenceTo>Cell__c</referenceTo>
    <relationshipLabel>Containers</relationshipLabel>
    <relationshipName>Containers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <description>Warehouse with parameters and capacity</description>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse__c/fields/Height_Containers__c.field-meta.xml
<CustomField>
    <fullName>Height_Containers__c</fullName>
    <label>Height Containers</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Length_Containers__c.field-meta.xml
<CustomField>
    <fullName>Length_Containers__c</fullName>
    <label>Length Containers</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Width_Containers__c.field-meta.xml
<CustomField>
    <fullName>Width_Containers__c</fullName>
    <label>Width Containers</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/recordTypes/Warehouse.recordType-meta.xml
<RecordType>
    <fullName>Warehouse</fullName>
    <active>true</active>
    <description>Regular warehouse</description>
    <label>Warehouse</label>
</RecordType>

force-app/main/default/objects/Warehouse_Cell__c/Warehouse_Cell__c.object-meta.xml
<CustomObject>
    <label>Warehouse Cell</label>
    <nameField>
        <label>Warehouse Cell Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouse Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse_Cell__c/fields/Is_Free__c.field-meta.xml
<CustomField>
    <fullName>Is_Free__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Free</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Warehouse_Cell__c/fields/Unique_Address__c.field-meta.xml
<CustomField>
    <fullName>Unique_Address__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Unique Address</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Warehouse_Cell__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Warehouse_Cells</relationshipLabel>
    <relationshipName>Warehouse_Cells</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ContainerAllocationService.cls
public with sharing class ContainerAllocationService {
    private Warehouse__c warehouse;
    private List<Warehouse_Cell__c> relatedCellList;
    private List<Warehouse_Cell__c> availableWCellList = new List<Warehouse_Cell__c>();

    public void initAllocationFlow(List<Container__c> containerList) {
        this.warehouse = [
            SELECT Id, Height_Containers__c, Width_Containers__c, Length_Containers__c 
            FROM Warehouse__c LIMIT 1
        ];

        this.relatedCellList = [
            SELECT Id, Unique_Address__c, Is_Free__c, (SELECT Id, Issuance_Date__c, Status__c FROM Containers__r) 
            FROM Warehouse_Cell__c
            WHERE Warehouse__c = :warehouse.Id
        ];

        for (Warehouse_Cell__c wCell : relatedCellList) {
            if (wCell.Is_Free__c) {
                this.availableWCellList.add(wCell);
            }
        }

        distributeContainers(containerList);
    }

    private void distributeContainers(List<Container__c> containerList) {
        List<Warehouse_Cell__c> cellListToUpdate = new List<Warehouse_Cell__c>();
        List<Container__c> containerListToUpdate = new List<Container__c>();

        for (Container__c container : containerList) {
            Warehouse_Cell__c availableWCell = this.availableWCellList.remove(0);
            availableWCell.Is_Free__c = false;
            cellListToUpdate.add(availableWCell);
            
            container.Warehouse_Cell__c = availableWCell.Id;
            container.Status__c = specifyNextStatus(container.Status__c);
            containerListToUpdate.add(container);
        }

        DMLExecutor.doUpdate(cellListToUpdate);
        DMLExecutor.doUpdate(containerListToUpdate);
    }

    private static String specifyNextStatus(String currentStatus) {
        return currentStatus == Constants.ARRIVED_FOR_ISSUANCE 
                ? Constants.AWAITING_ISSUANCE 
                : currentStatus == Constants.ARRIVED_FOR_SHIPMENT 
                    ? Constants.AWAITING_SHIPMENT 
                    : currentStatus;
    }

}