force-app/main/default/objects/Container__c/Container__c.object-meta.xml
<CustomObject>
    <label>Container</label>
    <nameField>
        <label>Container Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Containers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Container__c/fields/Arrival_Date__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Date__c</fullName>
    <label>Arrival Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Container__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Containers</relationshipLabel>
    <relationshipName>Containers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Container__c/fields/Contact_Ext_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Ext_Id__c</fullName>
    <label>Contact Ext Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Container__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Arrived for issuance</fullName>
            </value>
            <value>
                <fullName>Arrived for shipment</fullName>
            </value>
            <value>
                <fullName>Awaiting issuance</fullName>
            </value>
            <value>
                <fullName>Awaiting shipment</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Выдан</fullName>
                <isActive>false</isActive>
                <label>Выдан</label>
            </value>
            <value>
                <fullName>Ожидает выдачи</fullName>
                <isActive>false</isActive>
                <label>Ожидает выдачи</label>
            </value>
            <value>
                <fullName>Ожидает отгрузки</fullName>
                <isActive>false</isActive>
                <label>Ожидает отгрузки</label>
            </value>
            <value>
                <fullName>Прибыл для выдачи</fullName>
                <isActive>false</isActive>
                <label>Прибыл для выдачи</label>
            </value>
            <value>
                <fullName>Прибыл на отгрузку</fullName>
                <isActive>false</isActive>
                <label>Прибыл на отгрузку</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContainerTRService.cls
public with sharing class ContainerTRService {
    
    public static void populateValuesOnArrival(List<Container__c> processingRecords) {

        for (Container__c container_i : processingRecords) {

            if (String.isBlank(container_i.Status__c)) {
                container_i.Status__c = 'Arrived For Delivery'; 
            }

            container_i.Arrival_Date__c = Datetime.now();
        }
    }
    
    public static void assignContacts(List<Container__c> processingRecords, Set<String> contactsExternalIds) {

        Map<String, Id> externalIdToContactIdMap = ContainerTRUtil.getExternalIdToContactIdMap(contactsExternalIds);

        for (Container__c container_i : processingRecords) {
            
            if (externalIdToContactIdMap.containsKey(container_i.Contact_Ext_Id__c)) {
                container_i.Contact__c = externalIdToContactIdMap.get(container_i.Contact_Ext_Id__c);
            }
        }
    }

    public static void scheduleContactAssignmentJob() {
        System.scheduleBatch(new ContactsCreationBatch(), 'ContactsCreationBatch', 5);
    }
}