force-app/main/default/objects/Container__c/Container__c.object-meta.xml
<CustomObject>
    <label>Container</label>
    <nameField>
        <label>Container Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Containers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Container__c/fields/Issuance_Date__c.field-meta.xml
<CustomField>
    <fullName>Issuance_Date__c</fullName>
    <label>Issuance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Container__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Arrived for issuance</fullName>
            </value>
            <value>
                <fullName>Arrived for shipment</fullName>
            </value>
            <value>
                <fullName>Awaiting issuance</fullName>
            </value>
            <value>
                <fullName>Awaiting shipment</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Выдан</fullName>
                <isActive>false</isActive>
                <label>Выдан</label>
            </value>
            <value>
                <fullName>Ожидает выдачи</fullName>
                <isActive>false</isActive>
                <label>Ожидает выдачи</label>
            </value>
            <value>
                <fullName>Ожидает отгрузки</fullName>
                <isActive>false</isActive>
                <label>Ожидает отгрузки</label>
            </value>
            <value>
                <fullName>Прибыл для выдачи</fullName>
                <isActive>false</isActive>
                <label>Прибыл для выдачи</label>
            </value>
            <value>
                <fullName>Прибыл на отгрузку</fullName>
                <isActive>false</isActive>
                <label>Прибыл на отгрузку</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Container__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Containers</relationshipLabel>
    <relationshipName>Containers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Container__c/fields/Warehouse_Cell__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Cell__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse Cell</label>
    <referenceTo>Cell__c</referenceTo>
    <relationshipLabel>Containers</relationshipLabel>
    <relationshipName>Containers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <description>Warehouse with parameters and capacity</description>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Address of Warehouse</description>
    <label>Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Height_Containers__c.field-meta.xml
<CustomField>
    <fullName>Height_Containers__c</fullName>
    <label>Height Containers</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Length_Containers__c.field-meta.xml
<CustomField>
    <fullName>Length_Containers__c</fullName>
    <label>Length Containers</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Width_Containers__c.field-meta.xml
<CustomField>
    <fullName>Width_Containers__c</fullName>
    <label>Width Containers</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/recordTypes/Warehouse.recordType-meta.xml
<RecordType>
    <fullName>Warehouse</fullName>
    <active>true</active>
    <description>Regular warehouse</description>
    <label>Warehouse</label>
</RecordType>

force-app/main/default/objects/Warehouse_Cell__c/Warehouse_Cell__c.object-meta.xml
<CustomObject>
    <label>Warehouse Cell</label>
    <nameField>
        <label>Warehouse Cell Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouse Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse_Cell__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <externalId>true</externalId>
    <label>Address</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Warehouse_Cell__c/fields/Is_Free__c.field-meta.xml
<CustomField>
    <fullName>Is_Free__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Free</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Warehouse_Cell__c/fields/Unique_Address__c.field-meta.xml
<CustomField>
    <fullName>Unique_Address__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Unique Address</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Warehouse_Cell__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Warehouse_Cells</relationshipLabel>
    <relationshipName>Warehouse_Cells</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/WarehouseStructure.cls
public with sharing class WarehouseStructure {
    private Integer width;
    private Integer height;
    private Integer length;

    // private Integer maxCellLevel;
    // private List<Warehouse_Cell__c> cellList;
    // private Map<Id, Container__c> cellIdToContainerMap;
    // private List<List<List<Warehouse_Cell__c>>> warehouseMatrix;
 
    public ContainerWarehouseStructure(Warehouse__c warehouse) {
        this.width = Integer.valueOf(warehouse.Width_Containers__c);
        this.height = Integer.valueOf(warehouse.Height_Containers__c);
        this.length = Integer.valueOf(warehouse.Length_Containers__c);

        // this.maxCellLevel = Integer.valueOf(warehouse.Max_Cell_Level__c);
        // this.cellList = obtainCellList(warehouse.Id);
        // this.cellIdToContainerMap = createCellIdToContainerMap();
        // this.warehouseMatrix = createWarehouseMatrix();
    }

    public Integer getWidth() {
        return this.width;
    }

    public Integer getHeight() {
        return this.height;
    }

    public Integer getLength() {
        return this.length;
    }

    // public Integer getMaxCellLevel() {
    //     return this.maxCellLevel;
    // }

    // public List<List<List<Warehouse_Cell__c>>> getWarehouseMatrix() {
    //     return this.warehouseMatrix;
    // }

    // public List<Warehouse_Cell__c> getCellList() {
    //     return this.cellList;
    // }

    // public Map<Id, Container__c> getCellIdToContainerMap() {
    //     return this.cellIdToContainerMap;
    // }

    private List<Warehouse_Cell__c> obtainCellListByWarehouseId(String warehouseId) {
        return [
            SELECT Unique_Address__c, Level__c, Is_Free__c, (SELECT Id, Issuance_Date__c, Status__c FROM Containers__r LIMIT 1) 
            FROM Warehouse_Cell__c
            WHERE Warehouse__c = :warehouseId
        ];
    }

    private Map<Id, Container__c> createCellIdToContainerMap() {
        Map<Id, Container__c> cellIdToContainerMap = new Map<Id, Container__c>();
        for (Warehouse_Cell__c cell : this.cellList) {
            if (cell.Containers__r.isEmpty()) {
                cellIdToContainerMap.put(cell.Id, null);
            } else {
                cellIdToContainerMap.put(cell.Id, cell.Containers__r[0]);
            }
        }
        return cellIdToContainerMap;
    }

    private List<List<List<Warehouse_Cell__c>>> createWarehouseMatrix() {
        List<List<List<Warehouse_Cell__c>>> matrix = new List<List<List<Warehouse_Cell__c>>>();

        for (Integer i = 0; i < width; i++) {
            List<List<Warehouse_Cell__c>> column = new List<List<Warehouse_Cell__c>>();
            for (Integer j = 0; j < length; j++) {
                List<Warehouse_Cell__c> row = new List<Warehouse_Cell__c>();
                for (Integer k = 0; k < maxCellLevel; k++) {
                    Warehouse_Cell__c cell = findCell(k + 1, i + 1, j + 1);
                    row.add(cell);
                }
                column.add(row);
            }
            matrix.add(column);
        }
        return matrix;
    }
    
    private Warehouse_Cell__c findCell(Integer level, Integer widthOffset, Integer column) {
        for (Warehouse_Cell__c cell : cellList) {
            Integer cellLevel = Integer.valueOf(cell.Level__c);
            Integer cellWidthOffset = convertLetterToNumber(cell.Address__c.substring(0, 1));
            Integer cellColumn = Integer.valueOf(cell.Address__c.substring(1, 2));
            
            if (cellLevel == level && cellWidthOffset == widthOffset && cellColumn == column) {
                return cell;
            }
        }
        return null;
    }

    private Integer convertLetterToNumber(String letter) {
        String alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
        Integer num = 0;
        for (Integer i = 0; i < letter.length(); i++) {
            Integer charIndex = alphabet.indexOf(letter.toUpperCase().substring(i, i+1)) + 1;
            num = (num * 26) + charIndex;
        }
        return num;
    }

}