force-app/main/default/objects/Cell__c/Cell__c.object-meta.xml
<CustomObject>
    <label>Cell</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Cell Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cell__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>TEXT(Width__c) &amp;  TEXT(Length__c) &amp;  TEXT(Level__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cell__c/fields/Container__c.field-meta.xml
<CustomField>
    <fullName>Container__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Container</label>
    <referenceTo>Container__c</referenceTo>
    <relationshipLabel>Cells</relationshipLabel>
    <relationshipName>Cells</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cell__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <formula>VALUE(RIGHT(Location__c, 1))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cell__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Free</fullName>
                <default>true</default>
                <label>Free</label>
            </value>
            <value>
                <fullName>Occupied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cell__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Cells</relationshipLabel>
    <relationshipName>Cells</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cell__c/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <label>Width</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Width</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Container__c/Container__c.object-meta.xml
<CustomObject>
    <label>Container</label>
    <nameField>
        <label>Container Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Containers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Container__c/fields/Date_Of_Issue__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Issue__c</fullName>
    <label>Date Of Issue</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Container__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Arrived for issuance</fullName>
            </value>
            <value>
                <fullName>Arrived for shipment</fullName>
            </value>
            <value>
                <fullName>Awaiting issuance</fullName>
            </value>
            <value>
                <fullName>Awaiting shipment</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Выдан</fullName>
                <isActive>false</isActive>
                <label>Выдан</label>
            </value>
            <value>
                <fullName>Ожидает выдачи</fullName>
                <isActive>false</isActive>
                <label>Ожидает выдачи</label>
            </value>
            <value>
                <fullName>Ожидает отгрузки</fullName>
                <isActive>false</isActive>
                <label>Ожидает отгрузки</label>
            </value>
            <value>
                <fullName>Прибыл для выдачи</fullName>
                <isActive>false</isActive>
                <label>Прибыл для выдачи</label>
            </value>
            <value>
                <fullName>Прибыл на отгрузку</fullName>
                <isActive>false</isActive>
                <label>Прибыл на отгрузку</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Container__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Containers</relationshipLabel>
    <relationshipName>Containers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Container__c/fields/Warehouse_Cell__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Cell__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse Cell</label>
    <referenceTo>Cell__c</referenceTo>
    <relationshipLabel>Containers</relationshipLabel>
    <relationshipName>Containers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <description>Warehouse with parameters and capacity</description>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Address of Warehouse</description>
    <label>Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Length__c.field-meta.xml
<CustomField>
    <fullName>Length__c</fullName>
    <label>Length</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Length</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <label>Width</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Width</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/CellDataWrapper.cls
public class CellDataWrapper {
    
    public Id cellId;
    public Id warehouseId;
    public Boolean isBufferZoneCell;
    public Container__c container;
    private Cell__c cell;

    public CellDataWrapper(Cell__c cell) {
        this.cellId = cell.Id;
        this.warehouseId = cell.Warehouse__c;
        this.cell = cell;

        if (!cell.Containers__r.isEmpty()) {
            this.container = cell.Containers__r.get(0);
        }

        this.isBufferZoneCell = (cell.Warehouse__r.RecordTypeId == WarehouseUtil.bufferZoneRTId);
    }

    public void setContainer(Container__c container) {
        this.container = container;
    }

    public Container__c getContainer() {
        return container;
    }

    public Boolean isContainerForShipment() {

        if (container == null || container.Status__c != 'Waiting For Shipment') {
            return false;
        }

        return true;
    }

    public Date getContainersDateOfIssue() {

        if (container == null) {
            return null;
        }

        return container.Date_Of_Issue__c;
    }

    public String getAddress() {
        return cell.Address__c;
    }

    public String getAddressOfThePreviousCell() {

        Integer level = getLevel();
        if (level == 1) {
            return null;
        }

        return WarehouseUtil.getCellAddress(getWidth(), getLength(), level - 1);
    }

    public String getAddressOfTheNextCell(Integer warehouseMaxLevel) {

        Integer level = getLevel();
        if (level == warehouseMaxLevel) {
            return null;
        }

        return WarehouseUtil.getCellAddress(getWidth(), getLength(), level + 1);
    }

    public Integer getLevel() {
        return Integer.valueOf(cell.Level__c);
    }

    public Integer getWidth() {
        return Integer.valueOf(cell.Width__c);
    }

    public Integer getLength() {
        return Integer.valueOf(cell.Length__c);
    }
}