force-app/main/default/objects/Cell__c/Cell__c.object-meta.xml
<CustomObject>
    <label>Cell</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Cell Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cell__c/fields/Container__c.field-meta.xml
<CustomField>
    <fullName>Container__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Container</label>
    <referenceTo>Container__c</referenceTo>
    <relationshipLabel>Cells</relationshipLabel>
    <relationshipName>Cells</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cell__c/fields/DeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDate__c</fullName>
    <label>DeliveryDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cell__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cell__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Free</fullName>
                <default>true</default>
                <label>Free</label>
            </value>
            <value>
                <fullName>Occupied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Container__c/Container__c.object-meta.xml
<CustomObject>
    <label>Container</label>
    <nameField>
        <label>Container Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Containers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Container__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Arrived for issuance</fullName>
            </value>
            <value>
                <fullName>Arrived for shipment</fullName>
            </value>
            <value>
                <fullName>Awaiting issuance</fullName>
            </value>
            <value>
                <fullName>Awaiting shipment</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Выдан</fullName>
                <isActive>false</isActive>
                <label>Выдан</label>
            </value>
            <value>
                <fullName>Ожидает выдачи</fullName>
                <isActive>false</isActive>
                <label>Ожидает выдачи</label>
            </value>
            <value>
                <fullName>Ожидает отгрузки</fullName>
                <isActive>false</isActive>
                <label>Ожидает отгрузки</label>
            </value>
            <value>
                <fullName>Прибыл для выдачи</fullName>
                <isActive>false</isActive>
                <label>Прибыл для выдачи</label>
            </value>
            <value>
                <fullName>Прибыл на отгрузку</fullName>
                <isActive>false</isActive>
                <label>Прибыл на отгрузку</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WarehouseTransaction__c/WarehouseTransaction__c.object-meta.xml
<CustomObject>
    <description>Represents any movement of containers</description>
    <label>WarehouseTransaction</label>
    <nameField>
        <displayFormat>WT-{000000}</displayFormat>
        <label>WarehouseTransaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WarehouseTransactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WarehouseTransaction__c/fields/Cell__c.field-meta.xml
<CustomField>
    <fullName>Cell__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cell</label>
    <referenceTo>Cell__c</referenceTo>
    <relationshipLabel>WarehouseTransactions</relationshipLabel>
    <relationshipName>WarehouseTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WarehouseTransaction__c/fields/Container__c.field-meta.xml
<CustomField>
    <fullName>Container__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Container</label>
    <referenceTo>Container__c</referenceTo>
    <relationshipLabel>WarehouseTransactions</relationshipLabel>
    <relationshipName>WarehouseTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CellHelper.cls
public with sharing class CellHelper {
    
    public static void cleanCellsForContainers(List<Container__c> containersList){
        List<WarehouseTransaction__c> transactionList = new List<WarehouseTransaction__c>();
        List<Cell__c> cellToUpdateList = new List<Cell__c>();

        List<Cell__c> cellList = CellSelector.getOccupiedCellsByContainers(containersList);
        for (Cell__c theCell: cellList){
            transactionList.add(WarehouseTransactionManager.createTransaction(theCell.Container__r, theCell.Id, theCell.Location__c, ''));

            theCell.Status__c = Cell.STATUS_FREE;
            theCell.DeliveryDate__c = null;
            theCell.Container__c = null;
            cellToUpdateList.add(theCell);
        }

        // Update cells and create transactions
        Savepoint sp = Database.setSavepoint();
        try {
            if (!cellToUpdateList.isEmpty()){
                update cellToUpdateList;
            }
            if (!transactionList.isEmpty()){
                insert transactionList;
            }
        } catch(exception ex){
            Database.rollback(sp);
            throw new DmlException(ex.getMessage());
        }
    }
}