force-app/main/default/objects/Cell__c/Cell__c.object-meta.xml
<CustomObject>
    <label>Cell</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Cell Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cell__c/fields/Container__c.field-meta.xml
<CustomField>
    <fullName>Container__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Container</label>
    <referenceTo>Container__c</referenceTo>
    <relationshipLabel>Cells</relationshipLabel>
    <relationshipName>Cells</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cell__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Free</fullName>
                <default>true</default>
                <label>Free</label>
            </value>
            <value>
                <fullName>Occupied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cell__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Cells</relationshipLabel>
    <relationshipName>Cells</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Container__c/Container__c.object-meta.xml
<CustomObject>
    <label>Container</label>
    <nameField>
        <label>Container Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Containers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Container__c/fields/Date_Of_Issue__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Issue__c</fullName>
    <label>Date Of Issue</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Container__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Arrived for issuance</fullName>
            </value>
            <value>
                <fullName>Arrived for shipment</fullName>
            </value>
            <value>
                <fullName>Awaiting issuance</fullName>
            </value>
            <value>
                <fullName>Awaiting shipment</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Выдан</fullName>
                <isActive>false</isActive>
                <label>Выдан</label>
            </value>
            <value>
                <fullName>Ожидает выдачи</fullName>
                <isActive>false</isActive>
                <label>Ожидает выдачи</label>
            </value>
            <value>
                <fullName>Ожидает отгрузки</fullName>
                <isActive>false</isActive>
                <label>Ожидает отгрузки</label>
            </value>
            <value>
                <fullName>Прибыл для выдачи</fullName>
                <isActive>false</isActive>
                <label>Прибыл для выдачи</label>
            </value>
            <value>
                <fullName>Прибыл на отгрузку</fullName>
                <isActive>false</isActive>
                <label>Прибыл на отгрузку</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Container__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Containers</relationshipLabel>
    <relationshipName>Containers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Container__c/fields/Warehouse_Cell__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Cell__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse Cell</label>
    <referenceTo>Cell__c</referenceTo>
    <relationshipLabel>Containers</relationshipLabel>
    <relationshipName>Containers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <description>Warehouse with parameters and capacity</description>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BufferContainerDistributionBatch.cls
public class BufferContainerDistributionBatch implements Database.Batchable<sObject>, Schedulable {

    private String query = 'SELECT Id'
                              + ', Status__c'
                              + ', Date_Of_Issue__c'
                        + ' FROM Container__c ';
    private String condition;
    private String order = ' ORDER BY Status__c, Date_Of_Issue__c ASC NULLS LAST';
    private Id bufferZoneRTId;

    public BufferContainerDistributionBatch() {
        this.query += ' WHERE Warehouse_Cell__r.Warehouse__r.RecordTypeId =: bufferZoneRTId';
        this.query += ' AND Status__c IN (\'Waiting For Delivery\', \'Waiting For Shipment\')';
        this.query += order;
    }

    public BufferContainerDistributionBatch(String condition) {
        this.condition = condition;
        query += condition != null ? condition : '';
        this.query += order;
    }

    public void execute(SchedulableContext sc) {
        if (String.isBlank(condition)) {
            Database.executeBatch(new BufferContainerDistributionBatch());
        } else {
            Database.executeBatch(new BufferContainerDistributionBatch(condition));
        } 
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {

        this.bufferZoneRTId = WarehouseUtil.bufferZoneRTId;
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<Container__c> scope) {

        System.debug('scope : ' + scope);
        WarehousesDataService whDataService = WarehousesDataService.getInstance();

        Map<Id, Container__c> containersToUpdate = new Map<Id, Container__c>();

        CellDataWrapper clientEmptyCell = null;
        CellDataWrapper shipmentEmptyCell = null;

        for (Container__c container_i : scope) {

            CellDataWrapper currentEmptyCell = null;

            if (container_i.Status__c == 'Waiting For Delivery') {
                clientEmptyCell = whDataService.getEmptyCellForClientContainer(container_i.Date_Of_Issue__c, clientEmptyCell?.warehouseId);
                currentEmptyCell = clientEmptyCell;
            } else {
                shipmentEmptyCell = whDataService.getEmptyCellForShipmentContainer(shipmentEmptyCell?.warehouseId);
                currentEmptyCell = shipmentEmptyCell;
            }

            if (currentEmptyCell.isBufferZoneCell) {
                break;
            }

            whDataService.placeContainerToCell(container_i, currentEmptyCell);
            containersToUpdate.put(container_i.Id, container_i);
        }

        if (containersToUpdate.isEmpty()) {
            return;
        }

        List<Container__c> lockedContainers = [SELECT Id FROM Container__c WHERE Id IN: containersToUpdate.keySet() FOR UPDATE];

        update containersToUpdate.values();
    }

    public void finish(Database.BatchableContext bc) {}
}