force-app/main/default/objects/Cell__c/Cell__c.object-meta.xml
<CustomObject>
    <label>Cell</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Cell Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cell__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>TEXT(Width__c) &amp;  TEXT(Length__c) &amp;  TEXT(Level__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cell__c/fields/Container__c.field-meta.xml
<CustomField>
    <fullName>Container__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Container</label>
    <referenceTo>Container__c</referenceTo>
    <relationshipLabel>Cells</relationshipLabel>
    <relationshipName>Cells</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cell__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <formula>VALUE(RIGHT(Location__c, 1))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cell__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Cells</relationshipLabel>
    <relationshipName>Cells</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cell__c/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <label>Width</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Width</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Container__c/Container__c.object-meta.xml
<CustomObject>
    <label>Container</label>
    <nameField>
        <label>Container Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Containers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Container__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Containers</relationshipLabel>
    <relationshipName>Containers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Container__c/fields/Warehouse_Cell__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Cell__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse Cell</label>
    <referenceTo>Cell__c</referenceTo>
    <relationshipLabel>Containers</relationshipLabel>
    <relationshipName>Containers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <description>Warehouse with parameters and capacity</description>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Address of Warehouse</description>
    <label>Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Length__c.field-meta.xml
<CustomField>
    <fullName>Length__c</fullName>
    <label>Length</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Length</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <label>Width</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Width</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warehouse__c/recordTypes/Warehouse.recordType-meta.xml
<RecordType>
    <fullName>Warehouse</fullName>
    <active>true</active>
    <description>Regular warehouse</description>
    <label>Warehouse</label>
</RecordType>

force-app/main/default/objects/Warehouse_Cell__c/Warehouse_Cell__c.object-meta.xml
<CustomObject>
    <label>Warehouse Cell</label>
    <nameField>
        <label>Warehouse Cell Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouse Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse_Cell__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <externalId>true</externalId>
    <label>Address</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Warehouse_Cell__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Warehouse_Cells</relationshipLabel>
    <relationshipName>Warehouse_Cells</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/WarehouseDataWrapper.cls
public class WarehouseDataWrapper {
    
    public Id warehouseId;
    private Warehouse__c warehouse;
    private List<String> orderedListOfEmptyCellsAddresses;
    private Map<Id, CellDataWrapper> cellIdToDataWrapperMap;
    private Map<Id, CellDataWrapper> emptyCellsMap;
    private Map<String, Id> cellAddressToIdMap;

    public WarehouseDataWrapper(Id warehouseId, List<Cell__c> cells) {

        this.warehouseId = warehouseId;
        this.orderedListOfEmptyCellsAddresses = new List<String>();
        this.cellIdToDataWrapperMap = new Map<Id, CellDataWrapper>();
        this.emptyCellsMap = new Map<Id, CellDataWrapper>();
        this.cellAddressToIdMap = new Map<String, Id>();

        if (String.isBlank(warehouseId)) {
            return;
        }

        for (Cell__c cell_i : cells) {
            
            if (cell_i.Warehouse__c != warehouseId) {
                continue;
            }

            if (this.warehouse == null) {
                this.warehouse = (Warehouse__c) cell_i.getSObject('Warehouse__r');
            }

            cellAddressToIdMap.put(cell_i.Address__c, cell_i.Id);

            CellDataWrapper cellDataWrapper = new CellDataWrapper(cell_i);

            if (cellDataWrapper.getContainer() == null) {
                orderedListOfEmptyCellsAddresses.add(cellDataWrapper.getAddress());
                emptyCellsMap.put(cellDataWrapper.cellId, cellDataWrapper);
            }
            
            cellIdToDataWrapperMap.put(cellDataWrapper.cellId, cellDataWrapper);
        }

        orderedListOfEmptyCellsAddresses.sort();
    }

    public CellDataWrapper getEmptyCell() {

        if (orderedListOfEmptyCellsAddresses.isEmpty()) {
            return null;
        }

        return emptyCellsMap.get(cellAddressToIdMap.get(orderedListOfEmptyCellsAddresses.get(0)));
    }

    public CellDataWrapper getEmptyCellForClientContainer(Date dateOfIssue) {

        if (orderedListOfEmptyCellsAddresses.isEmpty()) {
            return null;
        }

        CellDataWrapper firstLevelCell = null;
        CellDataWrapper cellWithPreviousCellWithBiggestOrEqualsDateOfIssue = null;

        for (CellDataWrapper cellDataWrapper_i : emptyCellsMap.values()) {
            
            if (cellDataWrapper_i.getLevel() == 1) {

                if (firstLevelCell == null) {
                    firstLevelCell = cellDataWrapper_i;
                }
                continue;
            }

            CellDataWrapper previousCell = getPreviousCell(cellDataWrapper_i);

            if (previousCell != null
                        && !previousCell.isContainerForShipment()
                        && ((previousCell.getContainersDateOfIssue() == null && previousCell.getContainer() != null)
                            || (previousCell.getContainersDateOfIssue() != null && previousCell.getContainersDateOfIssue() >= dateOfIssue))) {
                    cellWithPreviousCellWithBiggestOrEqualsDateOfIssue = cellDataWrapper_i;
                break;
            }
        }

        CellDataWrapper emptyCellForClientContainer = null;

        if (cellWithPreviousCellWithBiggestOrEqualsDateOfIssue != null) {
            emptyCellForClientContainer = cellWithPreviousCellWithBiggestOrEqualsDateOfIssue;
        } else if (firstLevelCell != null) {
            emptyCellForClientContainer = firstLevelCell;
        }

        return emptyCellForClientContainer;
    }

    public CellDataWrapper getEmptyCellForShipmentContainer() {

        if (orderedListOfEmptyCellsAddresses.isEmpty()) {
            return null;
        }

        CellDataWrapper firstLevelCell = null;
        CellDataWrapper cellWithPreviousCellForShipment = null;

        for (CellDataWrapper cellDataWrapper_i : emptyCellsMap.values()) {
            
            if (cellDataWrapper_i.getLevel() == 1) {

                if (firstLevelCell == null) {
                    firstLevelCell = cellDataWrapper_i;
                }
                continue;
            }

            CellDataWrapper previousCell = getPreviousCell(cellDataWrapper_i);

            if (previousCell != null && previousCell.isContainerForShipment()) {
                cellWithPreviousCellForShipment = cellDataWrapper_i;
                break;
            }
        }

        CellDataWrapper emptyCellForShipmentContainer = null;

        if (cellWithPreviousCellForShipment != null) {
            emptyCellForShipmentContainer = cellWithPreviousCellForShipment;
        } else if (firstLevelCell != null) {
            emptyCellForShipmentContainer = firstLevelCell;
        }

        return emptyCellForShipmentContainer;
    }

    public Integer getAmountOfEmptyCells() {
        return orderedListOfEmptyCellsAddresses.size();
    }

    public void placeContainerToCell(Container__c container, CellDataWrapper cellDataWrapper) {

        container.Warehouse_Cell__c = cellDataWrapper.cellId;

        cellIdToDataWrapperMap.get(cellDataWrapper.cellId).setContainer(container);
        emptyCellsMap.remove(cellDataWrapper.cellId);

        Integer elementIndex = orderedListOfEmptyCellsAddresses.indexOf(cellDataWrapper.getAddress());
        if (elementIndex != -1) {
            orderedListOfEmptyCellsAddresses.remove(elementIndex);
            orderedListOfEmptyCellsAddresses.sort();
        }
    }

    public void removeContainerFromCell(Container__c container, CellDataWrapper cellDataWrapper) {

        container.Warehouse_Cell__c = null;

        cellIdToDataWrapperMap.get(cellDataWrapper.cellId).setContainer(null);
        emptyCellsMap.put(cellDataWrapper.cellId, cellDataWrapper);
        
        Integer elementIndex = orderedListOfEmptyCellsAddresses.indexOf(cellDataWrapper.getAddress());
        if (elementIndex == -1) {
            orderedListOfEmptyCellsAddresses.add(cellDataWrapper.getAddress());
            orderedListOfEmptyCellsAddresses.sort();
        }
    }

    public CellDataWrapper getPreviousCell(CellDataWrapper currentCell) {

        String addressOfThePreviousCell = currentCell.getAddressOfThePreviousCell();

        if (String.isBlank(addressOfThePreviousCell) || !cellAddressToIdMap.containsKey(addressOfThePreviousCell)) {
            return null;
        }

        return cellIdToDataWrapperMap.get(cellAddressToIdMap.get(addressOfThePreviousCell));
    }

    public CellDataWrapper getNextCell(CellDataWrapper currentCell) {

        String addressOfTheNextCell = currentCell.getAddressOfTheNextCell(getLevel());

        if (String.isBlank(addressOfTheNextCell) || !cellAddressToIdMap.containsKey(addressOfTheNextCell)) {
            return null;
        }

        return cellIdToDataWrapperMap.get(cellAddressToIdMap.get(addressOfTheNextCell));
    }

    public CellDataWrapper getCell(Id cellId) {
        return cellIdToDataWrapperMap.get(cellId);
    }

    public Integer getLevel() {
        return Integer.valueOf(warehouse.Level__c);
    }

    public Integer getWidth() {
        return Integer.valueOf(warehouse.Width__c);
    }

    public Integer getLength() {
        return Integer.valueOf(warehouse.Length__c);
    }
}