force-app/main/default/objects/Cell__c/Cell__c.object-meta.xml
<CustomObject>
    <label>Cell</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Cell Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cell__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cell__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Free</fullName>
                <default>true</default>
                <label>Free</label>
            </value>
            <value>
                <fullName>Occupied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cell__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Cells</relationshipLabel>
    <relationshipName>Cells</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cell__c/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <label>Width</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Width</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <description>Warehouse with parameters and capacity</description>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <formula>Heigth__c *  Length__c *  Width__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Heigth__c.field-meta.xml
<CustomField>
    <fullName>Heigth__c</fullName>
    <label>Heigth</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Length__c.field-meta.xml
<CustomField>
    <fullName>Length__c</fullName>
    <label>Length</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Length</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <label>Width</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Width</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warehouse__c/recordTypes/Warehouse.recordType-meta.xml
<RecordType>
    <fullName>Warehouse</fullName>
    <active>true</active>
    <description>Regular warehouse</description>
    <label>Warehouse</label>
</RecordType>

force-app/main/default/classes/WarehouseTriggerHandler.cls
public with sharing class WarehouseTriggerHandler {
    public void handleAfterInsert(List<Warehouse__c> newWarehouseList) {
        createCells(newWarehouseList);
    }

    public void handleAfterUpdate(List<Warehouse__c> newWarehouseList, Map<Id, Warehouse__c> oldWarehouseMap) {
        List<Id> warehouseIdList = new List<Id>();
        List<Warehouse__c> warehouseToRefreshCellsList = new List<Warehouse__c>();
        for (Warehouse__c warehouse : newWarehouseList) {
            if (warehouse.Heigth__c != oldWarehouseMap.get(warehouse.Id).Heigth__c ||
                warehouse.Length__c != oldWarehouseMap.get(warehouse.Id).Length__c ||
                warehouse.Width__c != oldWarehouseMap.get(warehouse.Id).Width__c) {
                    warehouseIdList.add(warehouse.Id);
                    warehouseToRefreshCellsList.add(warehouse);
            }
        }
        if (!warehouseIdList.isEmpty()){
            deleteCells(warehouseIdList);
        }

        if (!warehouseToRefreshCellsList.isEmpty()){
            createCells(warehouseToRefreshCellsList);
        }
    }

    private void createCells(List<Warehouse__c> warehouseList) {
        List<Cell__c> cellList = new List<Cell__c>();
        for (Warehouse__c warehouse : warehouseList) {
            Integer wWidth = (Integer)warehouse.Width__c;
            Integer wLenght = (Integer)warehouse.Length__c;
            Integer wHeight = (Integer)warehouse.Heigth__c;

            for (Integer i = 0; i < warehouse.Capacity__c; i++) {
                String currentWidth = WarehouseHelper.getWidthMapping().get(wWidth);
                Cell__c cell = new Cell__c(
                    Warehouse__c = warehouse.Id, 
                    Status__c = Cell.STATUS_FREE, 
                    Location__c = currentWidth + wLenght + 'L' + wHeight
                );
                cellList.add(cell);

                wHeight -= 1;
                if (wHeight <= 0){
                    wHeight = (Integer)warehouse.Heigth__c;
                    wLenght -= 1;
                    if (wLenght <= 0){
                        wLenght = (Integer)warehouse.Length__c;
                        wWidth -= 1;
                    }
                }
            }
        }
        insert cellList;
    }

    private void deleteCells(List<Id> warehouseIdList) {
        delete [SELECT Id FROM Cell__c WHERE Warehouse__c IN :warehouseIdList];
    }
}