force-app/main/default/objects/Cell__c/Cell__c.object-meta.xml
<CustomObject>
    <label>Cell</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Cell Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cell__c/fields/Column__c.field-meta.xml
<CustomField>
    <fullName>Column__c</fullName>
    <formula>LEFT(Location__c, 2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Column</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cell__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <formula>VALUE(RIGHT(Location__c, 1))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CellTriggerHandler.cls
public without sharing class CellTriggerHandler {
    
    public void onBeforeInsert(List<Cell__c> newCells) {
        calculateCode(newCells, null);
    }

    public void onBeforeUpdate(List<Cell__c> newCells, Map<Id, Cell__c> oldCells) {
        calculateCode(newCells, oldCells);
    }

    private void calculateCode(List<Cell__c> cells, Map<Id, Cell__c> oldCells) {
        for (Cell__c cell : cells) {
            if (oldCells == null || 
                cell.Row__c != oldCells.get(cell.Id).Row__c ||
                cell.Column__c != oldCells.get(cell.Id).Column__c ||
                cell.Level__c != oldCells.get(cell.Id).Level__c) {

                cell.Code__c = cell.Row__c + String.valueOf(cell.Column__c + 1) + 'L' + String.valueOf(cell.Level__c + 1);
            }
        }
    }

}