force-app/main/default/objects/Cell__c/Cell__c.object-meta.xml
<CustomObject>
    <label>Cell</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Cell Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cell__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>TEXT(Width__c) &amp;  TEXT(Length__c) &amp;  TEXT(Level__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cell__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <formula>VALUE(RIGHT(Location__c, 1))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cell__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Cells</relationshipLabel>
    <relationshipName>Cells</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cell__c/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <label>Width</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Width</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <description>Warehouse with parameters and capacity</description>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Address of Warehouse</description>
    <label>Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Length__c.field-meta.xml
<CustomField>
    <fullName>Length__c</fullName>
    <label>Length</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Length</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <label>Width</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Width</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/WarehouseTRService.cls
public with sharing class WarehouseTRService {

    public static void createCells(List<Warehouse__c> processingRecords, Boolean isUpdate) {

        List<Cell__c> cellsToInsert = new List<Cell__c>();

        Map<Id, Set<String>> whIdToExistedCellAddressesMap;

        if (isUpdate) {
            whIdToExistedCellAddressesMap = WarehouseUtil.getWarehouseIdToExistedCellAddressesMap(processingRecords);
        }

        for (Warehouse__c warehouse_i : processingRecords) {
            
            Set<String> addressesOfExistedCellsForCurWarehouse;

            if (isUpdate) {
                addressesOfExistedCellsForCurWarehouse = whIdToExistedCellAddressesMap.get(warehouse_i.Id);
            }

            Integer whWidth = Integer.valueOf(warehouse_i.Width__c);
            Integer whLength = Integer.valueOf(warehouse_i.Length__c);
            Integer whLevel = Integer.valueOf(warehouse_i.Level__c);

            for (Integer width_i = 1; width_i <= whWidth; width_i++) {
                for (Integer length_j = 1; length_j <= whLength; length_j++) {
                    for (Integer level_k = 1; level_k <= whLevel; level_k++) {

                        String address = WarehouseUtil.getCellAddress(width_i, length_j, level_k);

                        if (isUpdate && addressesOfExistedCellsForCurWarehouse.contains(address)) {
                            continue;
                        }

                        Cell__c cell = new Cell__c(
                            Name = warehouse_i.Name + ' ' + address,
                            Warehouse__c = warehouse_i.Id,
                            Width__c = String.valueOf(width_i),
                            Length__c = String.valueOf(length_j),
                            Level__c = String.valueOf(level_k),
                            Address__c = address
                        );
                        cellsToInsert.add(cell);
                    }
                }
            }
        }

        if (cellsToInsert.isEmpty()) {
            return;
        }

        insert cellsToInsert;
    }

    public static void updateCellsNames(List<Warehouse__c> processingRecords) {

        Map<Id, List<Cell__c>> warehouseIdToExistedCellsMap = WarehouseUtil.getWarehouseIdToExistedCellsMap(processingRecords);

        List<Cell__c> cellsToUpdate = new List<Cell__c>();

        for (Warehouse__c warehouse_i : processingRecords) {
            
            for (Cell__c cell_j : warehouseIdToExistedCellsMap.get(warehouse_i.Id)) {
                cell_j.Name = warehouse_i.Name + ' ' + cell_j.Address__c;
                cellsToUpdate.add(cell_j);
            }
        }

        if (cellsToUpdate.isEmpty()) {
            return;
        }

        update cellsToUpdate;
    }
}