force-app/main/default/objects/Cell__c/Cell__c.object-meta.xml
<CustomObject>
    <label>Cell</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Cell Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cell__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>TEXT(Width__c) &amp;  TEXT(Length__c) &amp;  TEXT(Level__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cell__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Cells</relationshipLabel>
    <relationshipName>Cells</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <description>Warehouse with parameters and capacity</description>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Address of Warehouse</description>
    <label>Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WarehouseTRUtil.cls
public with sharing class WarehouseTRUtil {
    
    //in order to convert width into the corresponding letter
    public static final Integer ASCII_CHARACTER_BASE = 64;

    public static Map<Id, Set<String>> getWarehouseIdToExistedCellAddressesMap(List<Warehouse__c> warehouses) {

        Map<Id, Set<String>> whIdToExistedCellAddressesMap = new Map<Id, Set<String>>();

        for (Cell__c cell_i : getExistedCells(warehouses)) {
            
            if (!whIdToExistedCellAddressesMap.containsKey(cell_i.Warehouse__c)) {
                whIdToExistedCellAddressesMap.put(cell_i.Warehouse__c, new Set<String>());
            }
            whIdToExistedCellAddressesMap.get(cell_i.Warehouse__c).add(cell_i.Address__c);
        }

        return whIdToExistedCellAddressesMap;
    }

    public static Map<Id, List<Cell__c>> getWarehouseIdToExistedCellsMap(List<Warehouse__c> warehouses) {

        Map<Id, List<Cell__c>> warehouseIdToExistedCellsMap = new Map<Id, List<Cell__c>>();

        for (Cell__c cell_i : getExistedCells(warehouses)) {
            
            if (!warehouseIdToExistedCellsMap.containsKey(cell_i.Warehouse__c)) {
                warehouseIdToExistedCellsMap.put(cell_i.Warehouse__c, new List<Cell__c>());
            }
            warehouseIdToExistedCellsMap.get(cell_i.Warehouse__c).add(cell_i);
        }

        return warehouseIdToExistedCellsMap;
    }

    public static List<Cell__c> getExistedCells(List<Warehouse__c> warehouses) {

        List<Cell__c> cells = [
            SELECT Id
                 , Warehouse__c
                 , Address__c
                 , Name
            FROM Cell__c
            WHERE Warehouse__c IN: warehouses
        ];

        return cells;
    }

    public static String getCellAddress(Integer width, Integer length, Integer level) {
        String address = String.fromCharArray(new List<Integer>{ASCII_CHARACTER_BASE + width}) + length + 'L' + level;
        return address;
    }
}