force-app/main/default/objects/Cell__c/Cell__c.object-meta.xml
<CustomObject>
    <label>Cell</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Cell Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cell__c/fields/Column__c.field-meta.xml
<CustomField>
    <fullName>Column__c</fullName>
    <formula>LEFT(Location__c, 2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Column</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cell__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <formula>VALUE(RIGHT(Location__c, 1))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cell__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Cells</relationshipLabel>
    <relationshipName>Cells</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <description>Warehouse with parameters and capacity</description>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warehouse__c/recordTypes/Warehouse.recordType-meta.xml
<RecordType>
    <fullName>Warehouse</fullName>
    <active>true</active>
    <description>Regular warehouse</description>
    <label>Warehouse</label>
</RecordType>

force-app/main/default/classes/WarehouseProcessorFeeder.cls
global without sharing class WarehouseProcessorFeeder implements Iterator<SObject>, Iterable<SObject> {

    List<Warehouse__c> warehouses;

    Integer warehouseIndex = 0;
    Integer rowIndex = 0;
    Integer columnIndex = 0;
    Integer levelIndex = 0;

    global Iterator<SObject> iterator() {
        return this;
    }
    
    global WarehouseProcessorFeeder(List<Warehouse__c> warehouses) {
        this.warehouses = warehouses;
    }
    
    global SObject next() {

        Warehouse__c warehouse = warehouses[warehouseIndex];

        Cell__c cell = new Cell__c();
        cell.Warehouse__c = warehouse.Id;
        cell.Row__c = getLetterCode(rowIndex);
        cell.Column__c = columnIndex;
        cell.Level__c = levelIndex;

        if (columnIndex == warehouse.Columns__c - 1) {
            columnIndex = 0;
            if (rowIndex == warehouse.Rows__c - 1) {
                rowIndex = 0;
                if (levelIndex == warehouse.Levels__c - 1) {
                    levelIndex = 0;
                    warehouseIndex++;
                } else {
                    levelIndex++;
                }
            } else {
                rowIndex++;
            }
        } else {
            columnIndex++;
        }

        return cell;
    }
    
    global boolean hasNext() {
        return warehouseIndex < warehouses.size();
    }

    private String getRowName(Integer rowIndex) {
        return getLetterCode(rowIndex);
    }
    
    private String getLetterCode(Integer index) {
        String[] letters = new String[]{'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'};
        String letterCode = '';
        while (index >= 0) {
            Integer remainder = Math.mod(index, 26);
            letterCode = letters[remainder] + letterCode;
            index = (index - remainder) / 26 - 1;
        }
        return letterCode;
    }
}