force-app/main/default/objects/Cell__c/Cell__c.object-meta.xml
<CustomObject>
    <label>Cell</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Cell Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cell__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>TEXT(Width__c) &amp;  TEXT(Length__c) &amp;  TEXT(Level__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cell__c/fields/Container__c.field-meta.xml
<CustomField>
    <fullName>Container__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Container</label>
    <referenceTo>Container__c</referenceTo>
    <relationshipLabel>Cells</relationshipLabel>
    <relationshipName>Cells</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cell__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <formula>VALUE(RIGHT(Location__c, 1))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cell__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Free</fullName>
                <default>true</default>
                <label>Free</label>
            </value>
            <value>
                <fullName>Occupied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cell__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Cells</relationshipLabel>
    <relationshipName>Cells</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cell__c/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <label>Width</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Width</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Container__c/Container__c.object-meta.xml
<CustomObject>
    <label>Container</label>
    <nameField>
        <label>Container Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Containers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Container__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Arrived for issuance</fullName>
            </value>
            <value>
                <fullName>Arrived for shipment</fullName>
            </value>
            <value>
                <fullName>Awaiting issuance</fullName>
            </value>
            <value>
                <fullName>Awaiting shipment</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Выдан</fullName>
                <isActive>false</isActive>
                <label>Выдан</label>
            </value>
            <value>
                <fullName>Ожидает выдачи</fullName>
                <isActive>false</isActive>
                <label>Ожидает выдачи</label>
            </value>
            <value>
                <fullName>Ожидает отгрузки</fullName>
                <isActive>false</isActive>
                <label>Ожидает отгрузки</label>
            </value>
            <value>
                <fullName>Прибыл для выдачи</fullName>
                <isActive>false</isActive>
                <label>Прибыл для выдачи</label>
            </value>
            <value>
                <fullName>Прибыл на отгрузку</fullName>
                <isActive>false</isActive>
                <label>Прибыл на отгрузку</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Container__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Containers</relationshipLabel>
    <relationshipName>Containers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Container__c/fields/Warehouse_Cell__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Cell__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse Cell</label>
    <referenceTo>Cell__c</referenceTo>
    <relationshipLabel>Containers</relationshipLabel>
    <relationshipName>Containers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <description>Warehouse with parameters and capacity</description>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Address of Warehouse</description>
    <label>Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Length__c.field-meta.xml
<CustomField>
    <fullName>Length__c</fullName>
    <label>Length</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Length</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <label>Width</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Width</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warehouse__c/recordTypes/Buffer_Zone.recordType-meta.xml
<RecordType>
    <fullName>Buffer_Zone</fullName>
    <active>true</active>
    <label>Buffer Zone</label>
</RecordType>

force-app/main/default/objects/Warehouse__c/recordTypes/Warehouse.recordType-meta.xml
<RecordType>
    <fullName>Warehouse</fullName>
    <active>true</active>
    <description>Regular warehouse</description>
    <label>Warehouse</label>
</RecordType>

force-app/main/default/objects/Warehouse_Cell__c/Warehouse_Cell__c.object-meta.xml
<CustomObject>
    <label>Warehouse Cell</label>
    <nameField>
        <label>Warehouse Cell Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouse Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse_Cell__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <externalId>true</externalId>
    <label>Address</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Warehouse_Cell__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Warehouse_Cells</relationshipLabel>
    <relationshipName>Warehouse_Cells</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/WarehousesDataService.cls
public class WarehousesDataService {
    
    private static String cellsQueryBase = 'SELECT Id'
                                              + ', Address__c'
                                              + ', Length__c'
                                              + ', Width__c'
                                              + ', Level__c'
                                              + ', Warehouse__c'
                                              + ', Warehouse__r.Length__c'
                                              + ', Warehouse__r.Width__c'
                                              + ', Warehouse__r.Level__c'
                                              + ', (SELECT Id, Status__c FROM Containers__r)'
                                        + ' FROM Cell__c'
                                        + ' WHERE Warehouse__r.RecordTypeId =: rtId';
    private static WarehousesDataService instance;
    private Id bufferZoneRTId;
    private Id warehouseRTId;
    private CellDataWrapper bufferZoneCell;
    private Map<Id, WarehouseDataWrapper> warehouseIdToDataWrapperMap;
    private List<Id> warehouseIdsWithEmptyCellsOrderedByAmountOfEmptyCells;
    private Id currentWarehouseWithEmptyCells;

    public class WarehousesDataWrapperException extends Exception {}

    private WarehousesDataService() {
        Map<String, Schema.RecordTypeInfo> devNameToRecordTypeInfoMap = Schema.SObjectType.Warehouse__c.getRecordTypeInfosByDeveloperName();
        this.bufferZoneRTId = devNameToRecordTypeInfoMap.get('Buffer_Zone').getRecordTypeId();
        this.warehouseRTId = devNameToRecordTypeInfoMap.get('Warehouse').getRecordTypeId();
        initData();
    }

    public static WarehousesDataService getInstance() {
        if(instance == null) {
            instance = new WarehousesDataService();
        }
        return instance;
    }

    public void refreshData() {
        initData();
    }

    public CellDataWrapper getEmptyCell() {

        if (warehouseIdsWithEmptyCellsOrderedByAmountOfEmptyCells.isEmpty()) {
            return bufferZoneCell;
        }

        if (currentWarehouseWithEmptyCells == null) {
            setCurrentWarehouseWithEmptyCells();
        }

        CellDataWrapper cell = warehouseIdToDataWrapperMap.get(currentWarehouseWithEmptyCells).getEmptyCell();
        return cell;
    }

    public CellDataWrapper getEmptyCellForShipmentContainer(Id warehouseId) {
        
        if (bufferZoneCell.warehouseId == warehouseId || warehouseIdsWithEmptyCellsOrderedByAmountOfEmptyCells.isEmpty()) {
            return bufferZoneCell;
        }

        if (warehouseId == null || !warehouseIdsWithEmptyCellsOrderedByAmountOfEmptyCells.contains(warehouseId)) {
            warehouseId = currentWarehouseWithEmptyCells;
        }

        WarehouseDataWrapper wdw = warehouseIdToDataWrapperMap.get(warehouseId);
        CellDataWrapper emptyCellForShipmentContainer = wdw.getEmptyCellForShipmentContainer();

        if (emptyCellForShipmentContainer != null) {
            return emptyCellForShipmentContainer;
        }

        for (Id warehouseId_i : warehouseIdsWithEmptyCellsOrderedByAmountOfEmptyCells) {
            
            if (warehouseId == warehouseId_i) {
                continue;
            }

            wdw = warehouseIdToDataWrapperMap.get(warehouseId);
            emptyCellForShipmentContainer = wdw.getEmptyCellForShipmentContainer();

            if (emptyCellForShipmentContainer != null) {
                break;
            }
        }

        if (emptyCellForShipmentContainer != null) {
            return emptyCellForShipmentContainer;
        }

        return bufferZoneCell;
    }

    public CellDataWrapper getPreviousCell(CellDataWrapper currentCell) {
        return warehouseIdToDataWrapperMap.get(currentCell.warehouseId).getPreviousCell(currentCell);
    }

    public CellDataWrapper getNextCell(CellDataWrapper currentCell) {
        return warehouseIdToDataWrapperMap.get(currentCell.warehouseId).getNextCell(currentCell);
    }

    public CellDataWrapper getCell(Id warehouseId, Id cellId) {
        return warehouseIdToDataWrapperMap.get(warehouseId).getCell(cellId);
    }

    public Integer getMaxLevelOfTheCurrentWherhouse() {
        return warehouseIdToDataWrapperMap.get(currentWarehouseWithEmptyCells).getLevel();
    }

    public void placeContainerToCell(Container__c container, CellDataWrapper cell) {

        if (cell.cellId == bufferZoneCell.cellId) {
            container.Warehouse_Cell__c = cell.cellId;
            return;
        }

        WarehouseDataWrapper wdw = warehouseIdToDataWrapperMap.get(cell.warehouseId);
        wdw.placeContainerToCell(container, cell);

        if (wdw.getAmountOfEmptyCells() == 0) {

            Integer elementIndex = warehouseIdsWithEmptyCellsOrderedByAmountOfEmptyCells.indexOf(wdw.warehouseId);
            if (elementIndex != -1) {
                warehouseIdsWithEmptyCellsOrderedByAmountOfEmptyCells.remove(elementIndex);
            }
            setCurrentWarehouseWithEmptyCells();
        }
    }

    public void removeContainerFromCell(Container__c container, CellDataWrapper cell) {

        if (cell.cellId == bufferZoneCell.cellId) {
            container.Warehouse_Cell__c = null;
            return;
        }

        warehouseIdToDataWrapperMap.get(cell.warehouseId).removeContainerFromCell(container, cell);
        setWarehouseIdsWithEmptyCellsOrderedByAmountOfEmptyCells();
    }

    private void initData() {

        setBufferZoneCell();
        setWarehouseIdToDataWrapperMap();
        setWarehouseIdsWithEmptyCellsOrderedByAmountOfEmptyCells();
        setCurrentWarehouseWithEmptyCells();
    }

    private void setBufferZoneCell() {
        this.bufferZoneCell = getBufferZoneCell();
    }

    private CellDataWrapper getBufferZoneCell() {

        String query = cellsQueryBase;
        query = query.replace('rtId', 'bufferZoneRTId');

        List<Cell__c> bufferCells = Database.query(query);

        Cell__c cell;
        if (bufferCells.isEmpty()) {
            insert new Warehouse__c(Name = 'Buffer Zone', RecordTypeId = bufferZoneRTId);
            cell = (Cell__c) Database.query(query);
        } else {
            cell = bufferCells.get(0);
        }

        return new CellDataWrapper(cell);
    }

    private void setWarehouseIdToDataWrapperMap() {
        this.warehouseIdToDataWrapperMap = getWarehouseIdToDataWrapperMap();
    }

    private Map<Id, WarehouseDataWrapper> getWarehouseIdToDataWrapperMap() {

        String query = cellsQueryBase;
        query = query.replace('rtId', 'warehouseRTId');
        query += ' ORDER BY Warehouse__c, Address__c';

        Map<Id, List<Cell__c>> warehouseIdToCellsMap = new Map<Id, List<Cell__c>>();

        for (Cell__c cell_i : Database.query(query)) {
            
            if (!warehouseIdToCellsMap.containsKey(cell_i.Warehouse__c)) {
                warehouseIdToCellsMap.put(cell_i.Warehouse__c, new List<Cell__c>());
            }
            warehouseIdToCellsMap.get(cell_i.Warehouse__c).add(cell_i);
        }

        if (warehouseIdToCellsMap.isEmpty()) {
            throw new WarehousesDataWrapperException('You need to create at least one Warehouse record with Warehouse record type');
        }

        Map<Id, WarehouseDataWrapper> warehouseIdToDataWrapperMap = new Map<Id, WarehouseDataWrapper>();

        for (Id warehouseId_i : warehouseIdToCellsMap.keySet()) {
            warehouseIdToDataWrapperMap.put(warehouseId_i, new WarehouseDataWrapper(warehouseId_i, warehouseIdToCellsMap.get(warehouseId_i)));
        }

        return warehouseIdToDataWrapperMap;
    }

    private void setWarehouseIdsWithEmptyCellsOrderedByAmountOfEmptyCells() {
        this.warehouseIdsWithEmptyCellsOrderedByAmountOfEmptyCells = getWarehouseIdsWithEmptyCellsOrderedByAmountOfEmptyCells();
    }

    private List<Id> getWarehouseIdsWithEmptyCellsOrderedByAmountOfEmptyCells() {

        List<Id> warehouseIdsWithEmptyCellsOrderedByAmountOfEmptyCells = new List<Id>();

        if (warehouseIdToDataWrapperMap.isEmpty()) {
            return warehouseIdsWithEmptyCellsOrderedByAmountOfEmptyCells;
        }

        Map<Integer, List<Id>> amountOfEmptyCellsToWarehouseIdsMap = new Map<Integer, List<Id>>();

        for (WarehouseDataWrapper wdw_i : warehouseIdToDataWrapperMap.values()) {
            
            Integer amountOfEmptyCells = wdw_i.getAmountOfEmptyCells();

            if (amountOfEmptyCells == 0) {
                continue;
            }

            if (!amountOfEmptyCellsToWarehouseIdsMap.containsKey(amountOfEmptyCells)) {
                amountOfEmptyCellsToWarehouseIdsMap.put(amountOfEmptyCells, new List<Id>());
            }
            amountOfEmptyCellsToWarehouseIdsMap.get(amountOfEmptyCells).add(wdw_i.warehouseId);
        }

        if (amountOfEmptyCellsToWarehouseIdsMap.isEmpty()) {
            return warehouseIdsWithEmptyCellsOrderedByAmountOfEmptyCells;
        }

        List<Integer> orderedAmounts = new List<Integer>(amountOfEmptyCellsToWarehouseIdsMap.keySet());
        orderedAmounts.sort();

        for (Integer amountOfEmptyCells_i : orderedAmounts) {
            warehouseIdsWithEmptyCellsOrderedByAmountOfEmptyCells.addAll(amountOfEmptyCellsToWarehouseIdsMap.get(amountOfEmptyCells_i));
        }

        return warehouseIdsWithEmptyCellsOrderedByAmountOfEmptyCells;
    }

    private void setCurrentWarehouseWithEmptyCells() {
        this.currentWarehouseWithEmptyCells = getCurrentWarehouseWithEmptyCells();
    }

    private Id getCurrentWarehouseWithEmptyCells() {

        if (warehouseIdsWithEmptyCellsOrderedByAmountOfEmptyCells.isEmpty()) {
            return null;
        }

        return warehouseIdsWithEmptyCellsOrderedByAmountOfEmptyCells.get(0);
    }
}