force-app/main/default/objects/Cell__c/Cell__c.object-meta.xml
<CustomObject>
    <label>Cell</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Cell Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cell__c/fields/Container__c.field-meta.xml
<CustomField>
    <fullName>Container__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Container</label>
    <referenceTo>Container__c</referenceTo>
    <relationshipLabel>Cells</relationshipLabel>
    <relationshipName>Cells</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cell__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Cells</relationshipLabel>
    <relationshipName>Cells</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Container__c/Container__c.object-meta.xml
<CustomObject>
    <label>Container</label>
    <nameField>
        <label>Container Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Containers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Container__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Source of container distribution</description>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Truck</fullName>
            </value>
            <value>
                <fullName>Ship</fullName>
                <default>true</default>
                <label>Ship</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Container__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Containers</relationshipLabel>
    <relationshipName>Containers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <description>Warehouse with parameters and capacity</description>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WarehouseTransaction__c/WarehouseTransaction__c.object-meta.xml
<CustomObject>
    <description>Represents any movement of containers</description>
    <label>WarehouseTransaction</label>
    <nameField>
        <displayFormat>WT-{000000}</displayFormat>
        <label>WarehouseTransaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WarehouseTransactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WarehouseTransaction__c/fields/Cell__c.field-meta.xml
<CustomField>
    <fullName>Cell__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cell</label>
    <referenceTo>Cell__c</referenceTo>
    <relationshipLabel>WarehouseTransactions</relationshipLabel>
    <relationshipName>WarehouseTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WarehouseTransaction__c/fields/Container__c.field-meta.xml
<CustomField>
    <fullName>Container__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Container</label>
    <referenceTo>Container__c</referenceTo>
    <relationshipLabel>WarehouseTransactions</relationshipLabel>
    <relationshipName>WarehouseTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WarehouseTransaction__c/fields/FromLocation__c.field-meta.xml
<CustomField>
    <fullName>FromLocation__c</fullName>
    <label>FromLocation</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WarehouseTransaction__c/fields/ToLocation__c.field-meta.xml
<CustomField>
    <fullName>ToLocation__c</fullName>
    <label>ToLocation</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WarehouseTransaction__c/fields/TransactionDate__c.field-meta.xml
<CustomField>
    <fullName>TransactionDate__c</fullName>
    <label>TransactionDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/WarehouseTransaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ship to Warehouse</fullName>
            </value>
            <value>
                <fullName>Truck to Warehouse</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WarehouseTransaction__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>WarehouseTransactions</relationshipLabel>
    <relationshipName>WarehouseTransactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/WarehouseTransactionManager.cls
public with sharing class WarehouseTransactionManager {

    public static WarehouseTransaction__c createTransaction(Container__c theContainer, Id cellId, String fromLocation, String toLocation) {
        String type = theContainer.Source__c == Container.SOURCE_IS_SHIP 
            ? WarehouseTransaction.TYPE_SHIP_TO 
            : WarehouseTransaction.TYPE_TRUCK_TO;
        if (toLocation == ''){
            type = WarehouseTransaction.TYPE_DELIVERED;
        }

        return new WarehouseTransaction__c(
                    Warehouse__c = theContainer.Warehouse__c,
                    Container__c = theContainer.Id,
                    Cell__c = cellId,
                    TransactionDate__c = System.now(),
                    FromLocation__c = fromLocation,
                    ToLocation__c = toLocation,
                    Type__c = type
                );
    }
}