force-app/main/default/objects/Cell__c/Cell__c.object-meta.xml
<CustomObject>
    <label>Cell</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Cell Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cell__c/fields/Column__c.field-meta.xml
<CustomField>
    <fullName>Column__c</fullName>
    <formula>LEFT(Location__c, 2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Column</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cell__c/fields/Container__c.field-meta.xml
<CustomField>
    <fullName>Container__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Container</label>
    <referenceTo>Container__c</referenceTo>
    <relationshipLabel>Cells</relationshipLabel>
    <relationshipName>Cells</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cell__c/fields/DeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDate__c</fullName>
    <label>DeliveryDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cell__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <formula>VALUE(RIGHT(Location__c, 1))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cell__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Free</fullName>
                <default>true</default>
                <label>Free</label>
            </value>
            <value>
                <fullName>Occupied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Container__c/Container__c.object-meta.xml
<CustomObject>
    <label>Container</label>
    <nameField>
        <label>Container Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Containers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Container__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Arrived for issuance</fullName>
            </value>
            <value>
                <fullName>Arrived for shipment</fullName>
            </value>
            <value>
                <fullName>Awaiting issuance</fullName>
            </value>
            <value>
                <fullName>Awaiting shipment</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Выдан</fullName>
                <isActive>false</isActive>
                <label>Выдан</label>
            </value>
            <value>
                <fullName>Ожидает выдачи</fullName>
                <isActive>false</isActive>
                <label>Ожидает выдачи</label>
            </value>
            <value>
                <fullName>Ожидает отгрузки</fullName>
                <isActive>false</isActive>
                <label>Ожидает отгрузки</label>
            </value>
            <value>
                <fullName>Прибыл для выдачи</fullName>
                <isActive>false</isActive>
                <label>Прибыл для выдачи</label>
            </value>
            <value>
                <fullName>Прибыл на отгрузку</fullName>
                <isActive>false</isActive>
                <label>Прибыл на отгрузку</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WarehouseHelper.cls
public with sharing class WarehouseHelper {

    // Method to find a target cell for a given container.
    public static Cell__c findTargetCellForContainer(Container__c theContainer, List<Cell__c> cellList) {
        // Initialize targetCell to null
        Cell__c targetCell = null;

        // Iterate through all cells in the warehouse
        for (Cell__c theCell : cellList) {
            // If the cell's level is one and the status is 'Free', assign the cell to the targetCell and break the loop
            if (theCell.Level__c == 1 && theCell.Status__c == Cell.STATUS_FREE) {
                targetCell = theCell;
                break;
            }

            // If the cell's level is one and it contains a container to be shipped, 
            // check if there is a free cell in the same column but on a different level
            else if (theCell.Level__c == 1 && theCell.Status__c == Cell.STATUS_OCCUPIED && theCell.Container__r.DeliveryDate__c != null) {
                for (Cell__c innerCell : cellList) {
                    // Check if the cell is in the same column but on a different level and is free
                    Boolean isTheSameColumn = innerCell.Column__c == theCell.Column__c;
                    Boolean notFirstCell = innerCell.Level__c > 1;
                    Boolean isFree = innerCell.Status__c == Cell.STATUS_FREE;
                    Boolean hasSameDeliveryDate = theContainer.DeliveryDate__c == theCell.Container__r.DeliveryDate__c;

                    if (isTheSameColumn && notFirstCell && isFree && hasSameDeliveryDate) {
                        // Move the container in cell to innerCell
                        targetCell = innerCell;
                        break;
                    }
                }
            }
        }
        return targetCell;
    }

    public static Map<Integer, String> getWidthMapping() {
        return new Map<Integer, String>{
            1 => 'A',
            2 => 'B',
            3 => 'C',
            4 => 'D',
            5 => 'E',
            6 => 'F',
            7 => 'G',
            8 => 'J',
            9 => 'H',
            10 => 'K'
        };
    }

    
    public static Date calculateDeliveryDate(Integer step, Integer containerSize, Boolean isFromShip){
        Date sundayDate = Date.today().toStartOfWeek().addDays(6);
        if (isFromShip){
            // Divide containers evenly by day of the week
            Integer deliveryDays = WarehouseManager.DELIVERY_DAYS;
            Integer containersPerDay = Math.round(containerSize / deliveryDays);
            Integer targetDay = containersPerDay > 0 
            ? (Integer)Math.floor(step / containersPerDay) - 1
            : 1;
            return sundayDate.addDays(targetDay);
        } else {
            // Calculate Sunday to deploy containers on the Ship
            return sundayDate;
        }
    }
}