force-app/main/default/objects/Contact/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>External Id of contact to associate with external Id on Container</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Container__c/Container__c.object-meta.xml
<CustomObject>
    <label>Container</label>
    <nameField>
        <label>Container Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Containers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Container__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Containers</relationshipLabel>
    <relationshipName>Containers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Container__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <label>ExternalId</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContainerService.cls
public with sharing class ContainerService {
    public static void updateContainerContacts(Set<String> contactExtIdSet) {   
        List<Container__c> containersToUpdateList = new List<Container__c>();

        Map<String, Contact> ExtIdToContactMap = ContactSelector.getExistingContactsByExtId(contactExtIdSet);

        for (Container__c container : [SELECT Id, Contact__c, ExternalId__c FROM Container__c WHERE ExternalId__c IN :contactExtIdSet]) {
            Contact contact = ExtIdToContactMap.get(container.ExternalId__c);
            if (contact != null) {
                container.Contact__c = contact.Id;
                containersToUpdateList.add(container);
            }
        }
        if (!containersToUpdateList.isEmpty()){
            update containersToUpdateList;
        }
    }
}