force-app/main/default/objects/Contact/fields/External_Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Contact_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Contact Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/External_ID_Container__c.field-meta.xml
<CustomField>
    <fullName>External_ID_Container__c</fullName>
    <externalId>true</externalId>
    <label>External ID Container</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Container__c/Container__c.object-meta.xml
<CustomObject>
    <label>Container</label>
    <nameField>
        <label>Container Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Containers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Container__c/fields/Arrival_Date__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Date__c</fullName>
    <label>Arrival Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Container__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Containers</relationshipLabel>
    <relationshipName>Containers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Container__c/fields/External_Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Contact_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Contact Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ContainerTriggerHandlerHelper.cls
public with sharing class ContainerTriggerHandlerHelper {
	private Map<String, Container__c> externalContactIdToContainerMap = new Map<String, Container__c>();
	private Boolean isPopulateContainersWithContact = false;
	private Boolean isDistributionOfContainersFromTheShip = false;

	public void populateArrivalDate(Container__c pContainer) {
		pContainer.Arrival_Date__c = date.today();
	}

	public void prepareContainerWithContact(Container__c pContainer) {
		if (pContainer.Contact__c == null && String.isNotBlank(pContainer.External_Contact_ID__c)) {
			externalContactIdToContainerMap.put(pContainer.External_Contact_ID__c, pContainer);
		}
	}

	public void checkPopulateContainersWithContact(Container__c pContainer) {
		if (pContainer.Contact__c == null && String.isNotBlank(pContainer.External_Contact_ID__c)) {
			isPopulateContainersWithContact = true;
		}
	}

	public void populateContainersWithContact() {
		Map<Id, Contact> contactMap = new Map<Id, Contact>(
			[
				SELECT Id
				FROM Contact
				WHERE External_ID_Container__c IN :externalContactIdToContainerMap.keySet()
			]
		);

		if (!contactMap.isEmpty()) {
			for (Id contactId_i : contactMap.keySet()) {
				Contact contact_i = contactMap.get(contactId_i);

				Container__c container = externalContactIdToContainerMap.get(
					contact_i.External_ID_Container__c
				);
				container.Contact__c = contactId_i;
			}
		}
	}

	public void populateContainersWithNewContact() {
		if (isPopulateContainersWithContact) {
			List<CronTrigger> scheduledJobs = [
				SELECT Id
				FROM CronTrigger
				WHERE CronJobDetail.Name = 'Container_PopulateWithContactBatch'
			];

			if (scheduledJobs.isEmpty()) {
				System.scheduleBatch(
					new Container_PopulateWithContactBatch(),
					'Container_PopulateWithContactBatch',
					5
				);
			}
		}
	}

	public void checkDistributionOfContainersFromTheShip(Container__c pContainer) {
		String dayOfWeek = pContainer.Arrival_Date__c.format('EEEE');
		if (dayOfWeek == 'Saturday') {
			isDistributionOfContainersFromTheShip = true;
		}
	}

	public void distributionOfContainersFromTheShip() {
		List<CronTrigger> scheduledJobs = [
			SELECT Id
			FROM CronTrigger
			WHERE CronJobDetail.Name = 'Container_DistributionFromTheShipBatch'
		];

		if (scheduledJobs.isEmpty()) {
			System.scheduleBatch(
				new Container_DistributionFromTheShipBatch(),
				'Container_DistributionFromTheShipBatch',
				5
			);
		}
	}
}