force-app/main/default/objects/Contact/fields/External_Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Contact_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Contact Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Id in the external system</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Container__c/Container__c.object-meta.xml
<CustomObject>
    <label>Container</label>
    <nameField>
        <label>Container Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Containers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Container__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Containers</relationshipLabel>
    <relationshipName>Containers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Container__c/fields/External_Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Contact_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Contact Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Container__c/fields/Issuance_Date__c.field-meta.xml
<CustomField>
    <fullName>Issuance_Date__c</fullName>
    <label>Issuance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Container__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Arrived for issuance</fullName>
            </value>
            <value>
                <fullName>Arrived for shipment</fullName>
            </value>
            <value>
                <fullName>Awaiting issuance</fullName>
            </value>
            <value>
                <fullName>Awaiting shipment</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Выдан</fullName>
                <isActive>false</isActive>
                <label>Выдан</label>
            </value>
            <value>
                <fullName>Ожидает выдачи</fullName>
                <isActive>false</isActive>
                <label>Ожидает выдачи</label>
            </value>
            <value>
                <fullName>Ожидает отгрузки</fullName>
                <isActive>false</isActive>
                <label>Ожидает отгрузки</label>
            </value>
            <value>
                <fullName>Прибыл для выдачи</fullName>
                <isActive>false</isActive>
                <label>Прибыл для выдачи</label>
            </value>
            <value>
                <fullName>Прибыл на отгрузку</fullName>
                <isActive>false</isActive>
                <label>Прибыл на отгрузку</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Container__c/fields/Warehouse_Cell__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Cell__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse Cell</label>
    <referenceTo>Cell__c</referenceTo>
    <relationshipLabel>Containers</relationshipLabel>
    <relationshipName>Containers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Container_Warehouse__c/Container_Warehouse__c.object-meta.xml
<CustomObject>
    <label>Container Warehouse</label>
    <nameField>
        <label>Container Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Container Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse_Cell__c/Warehouse_Cell__c.object-meta.xml
<CustomObject>
    <label>Warehouse Cell</label>
    <nameField>
        <label>Warehouse Cell Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouse Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse_Cell__c/fields/Container_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Container_Warehouse__c</fullName>
    <label>Container Warehouse</label>
    <referenceTo>Container_Warehouse__c</referenceTo>
    <relationshipLabel>Warehouse Cells</relationshipLabel>
    <relationshipName>Warehouse_Cells</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Warehouse_Cell__c/fields/Is_Empty__c.field-meta.xml
<CustomField>
    <fullName>Is_Empty__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Empty</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ContainerTriggerHandler.cls
/**
 * @description  Trigger handler for the Container object.
 * @author Kostiantyn Murin
 * @date 18-06-2023
 */
public class ContainerTriggerHandler implements ITriggerHandler {

    private static final List<String> AWAITING_STATUSES_LIST = new List<String>{ 'Awaiting issuance', 'Awaiting shipment' };
    private static final List<String> ARRIVED_STATUSES_LIST = new List<String>{ 'Arrived for issuance', 'Arrived for shipment' };
    
    /**
     * @description   Before insertion helper method
     * @author Kostiantyn Murin
     * @date 18-06-2023
     * @param newList List<SObject>
     */
    public void beforeInsert(List<SObject> newList) {
        processContainerItems(newList);
    }

    /**
     * @description   Before updation helper method
     * @author Kostiantyn Murin
     * @date 18-06-2023
     * @param newMap Map<Id, SObject> newMap
     * @param oldMap Map<Id, SObject> newMap
     */
    public void beforeUpdate(Map<Id, SObject> newMap, Map<Id, SObject> oldMap) {
        removeContainerCellRelation(newMap.values(), oldMap);
    }

    /**
     * @description   Before deletion helper method
     * @author Kostiantyn Murin
     * @date 18-06-2023
     * @param oldMap Map<Id, SObject> newMap
     */
    public void beforeDelete(Map<Id, SObject> oldMap) {}

    /**
     * @description   After insertion helper method
     * @author Kostiantyn Murin
     * @date 18-06-2023
     * @param newMap Map<Id, SObject> newMap
     */
    public void afterInsert(Map<Id, SObject> newMap) {
        runContactCreatorBatch();
        publishPlatformEvent(newMap.values());
    }

    /**
     * @description   After updation helper method
     * @author Kostiantyn Murin
     * @date 18-06-2023
     * @param newMap Map<Id, SObject> newMap
     * @param oldMap Map<Id, SObject> newMap
     */
    public void afterUpdate(Map<Id, SObject> newMap, Map<Id, SObject> oldMap) {
        updateRelatedCell(newMap.values(), oldMap);
    }

    /**
     * @description   After deletion helper method
     * @author Kostiantyn Murin
     * @date 18-06-2023
     * @param oldMap Map<Id, SObject> newMap
     */
    public void afterDelete(Map<Id, SObject> oldMap) {
        updateRelatedCell(oldMap.values());
    }

    /**
     * @description   After undeletion helper method
     * @author Kostiantyn Murin
     * @date 18-06-2023
     * @param newMap Map<Id, SObject> newMap
     * @param oldMap Map<Id, SObject> newMap
     */
    public void afterUndelete(Map<Id, SObject> oldMap) {}

    private static void processContainerItems(List<Container__c> newList) {

        Map<String, List<Container__c>>  containersByContactExtIdMap = new Map<String, List<Container__c>>();
        for (Container__c container : newList) {
            container.Delivery_Date__c = Date.today();
            setContainerStatus(container);
            setIssuanceDate(container);
            fillContainersByContactExtIdMap(container, containersByContactExtIdMap);
        }

        Map<String, SObject> existingContactByExternalIdMap = new Map<String, SObject>(
            [SELECT External_Id__c Id, Id contactId 
             FROM Contact 
             WHERE External_Id__c IN :containersByContactExtIdMap.keySet()
             AND External_Id__c != null
             GROUP BY External_Id__c, Id]
        );
        assignContact(existingContactByExternalIdMap, containersByContactExtIdMap);
    }

    private static void setContainerStatus(Container__c container) {
        if (container.Status__c == null) {
            container.Status__c = 'Arrived for issuance';
        }
    }

    private static void setIssuanceDate(Container__c container) {
        if (container.Status__c == 'Arrived for issuance') {
            container.Issuance_Date__c = Date.today().addDays(2 + (Integer)Math.floor(Math.random() * 5));
        }
    }

    private static void fillContainersByContactExtIdMap(Container__c container, Map<String, List<Container__c>>  containersByContactExtIdMap) {
        if (containersByContactExtIdMap.containsKey(container.External_Contact_ID__c)) {
            containersByContactExtIdMap.get(container.External_Contact_ID__c).add(container);
        } else {
            containersByContactExtIdMap.put(container.External_Contact_ID__c, new List<Container__c>{ container });
        }
    }

    private static void assignContact(Map<String, SObject> existingContactByExternalIdMap, Map<String, List<Container__c>>  containersByContactExtIdMap) {
        for (String contactExtId : existingContactByExternalIdMap.keySet()) {
            for (Container__c container : containersByContactExtIdMap.get(contactExtId)) {
                container.Contact__c = (String)existingContactByExternalIdMap.get(contactExtId).get('contactId');
            }
        }
    }

    private static void runContactCreatorBatch() {
        DataBase.executeBatch(new ContactCreatorBatch(), 50);
    }

    private static void removeContainerCellRelation(List<Container__c> newList, Map<Id, SObject> oldMap) {
        for (Container__c container : newList) {
            if (container.Status__c != oldMap.get(container.Id).get('Status__c') && container.Status__c == 'Issued') {
                container.Warehouse_Cell__c = null;
            }
        }
    }

    private static void updateRelatedCell(List<Container__c> newList, Map<Id, SObject> oldMap) {
        List<Warehouse_Cell__c> cellToUpdateList = new List<Warehouse_Cell__c>();
        Set<Date> issuanceDateSet = new Set<Date>();
        for (Container__c container : newList) {
            if (container.Status__c != oldMap.get(container.Id).get('Status__c') && container.Status__c == 'Issued' && container.Warehouse_Cell__c == null) {
                issuanceDateSet.add(container.Issuance_Date__c);
                cellToUpdateList.add(
                    new Warehouse_Cell__c(
                        Id = (Id)oldMap.get(container.Id).get('Warehouse_Cell__c'),
                        Is_Empty__c = true
                    )
                );
            }
        }
        DMLExecutor.doUpdate(cellToUpdateList);
    }

    private void publishPlatformEvent(List<Container__c> newList) {
        Boolean isUnlocatedContainerCreated = false;
        for (Container__c container : newList) {
            if (ARRIVED_STATUSES_LIST.contains(container.Status__c) && container.Warehouse_Cell__c == null) {
                isUnlocatedContainerCreated = true;
                break;
            }
        }
        if (isUnlocatedContainerCreated) {
            Map<Id, Container_Warehouse__c> warehouseMap = new Map<Id, Container_Warehouse__c>([
                SELECT Id FROM Container_Warehouse__c
            ]);
            PlatformEventBuilder.publishUnlocatedContainersCreatedEvent(warehouseMap.keySet());
        }
    }

    private void updateRelatedCell(List<Container__c> oldList) {
        List<Warehouse_Cell__c> cellToUpdateList = new List<Warehouse_Cell__c>();
        for (Container__c container : oldList) {
            if (container.Warehouse_Cell__c == null) {
                continue;
            }
            cellToUpdateList.add(
                new Warehouse_Cell__c(
                    Id = container.Warehouse_Cell__c,
                    Is_Empty__c = true
                )
            );
        }
        DMLExecutor.doUpdate(cellToUpdateList);
    }
}