force-app/main/default/objects/Contact/fields/External_Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Contact_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Contact Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Container__c/Container__c.object-meta.xml
<CustomObject>
    <label>Container</label>
    <nameField>
        <label>Container Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Containers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Container__c/fields/Arrival_Date__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Date__c</fullName>
    <label>Arrival Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Container__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Containers</relationshipLabel>
    <relationshipName>Containers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Container__c/fields/External_Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Contact_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Contact Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ExternalUserContactCreationBatch.cls
/**
 * @description The class makes external system calls to obtain information about the user,
 *               which allows to create contacts and associate them with containers.
 * @author Oleg Bezrukov
 * @date 07-2023
 */
public with sharing class ExternalUserContactCreationBatch implements Database.Batchable<SObject>, Database.AllowsCallouts, Database.Stateful {
    
    private Map<String, Contact> extCntIdToContactMap = new Map<String, Contact>();
    private List<Container__c> containerListToUpdate = new List<Container__c>();
    
    /**
     * @author Oleg Bezrukov
     * @date 07-2023
     */
    public Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id, Contact__c, Arrival_Date__c, External_Contact_Id__c ' + 
                        'FROM Container__c ' + 
                        'WHERE Contact__c = null ' + 
                                'AND External_Contact_Id__c != null';
        return Database.getQueryLocator(query);
    }
 
    /**
     * @description External system callouts and insertion of new contact records.
     * @author Oleg Bezrukov
     * @date 07-2023
     */
    public void execute(Database.BatchableContext BC, List<SObject> scope) {
        List<Contact> contactListToInsert = new List<Contact>();
        for (SObject sObj : scope) {
            Container__c container = (Container__c)sObj;
            if (!this.extCntIdToContactMap.containsKey(container.External_Contact_Id__c)) {
                Contact newCntToInsert = RandomUserService.obtainContactByRandomUser(container.External_Contact_Id__c);
                this.extCntIdToContactMap.put(container.External_Contact_Id__c, newCntToInsert);
                contactListToInsert.add(newCntToInsert);
            }
        }
        DMLExecutor.doInsert(contactListToInsert);
        this.containerListToUpdate.addAll((List<Container__c>)scope);
    }
 
    /**
     * @description Associate Contact with Container
     * @author Oleg Bezrukov
     * @date 07-2023
     */
    public void finish(Database.BatchableContext BC) {
        for (Container__c container : this.containerListToUpdate) {
            if (this.extCntIdToContactMap.containsKey(container.External_Contact_ID__c)) {
                container.Contact__c = this.extCntIdToContactMap.get(container.External_Contact_ID__c).Id;
            }
        }
        DMLExecutor.doUpdate(this.containerListToUpdate);
        // Database.executeBatch(new ContainerDistributorBatch(), 200);
    }
}