force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <description>Warehouse with parameters and capacity</description>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse__c/fields/Length__c.field-meta.xml
<CustomField>
    <fullName>Length__c</fullName>
    <label>Length</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Length</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <label>Width</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Width</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/WarehouseTRDispatcher.cls
public with sharing class WarehouseTRDispatcher {
    
    public static void createCells(List<Warehouse__c> processingRecords, Map<Id, Warehouse__c> oldMap) {
        System.debug('WarehouseTRDispatcher => createCells');

        List<Warehouse__c> warehousesToCreateCells = new List<Warehouse__c>();

        if (oldMap == null) {
            warehousesToCreateCells.addAll(processingRecords);
        } else {
            
            for (Warehouse__c wh_i : processingRecords) {

                Warehouse__c whOld = oldMap.get(wh_i.Id);
    
                if (wh_i.Width__c != whOld.Width__c ||
                        wh_i.Length__c != whOld.Length__c ||
                        wh_i.Level__c != whOld.Level__c) {
                    warehousesToCreateCells.add(wh_i);
                }
            }
        }

        if (warehousesToCreateCells.isEmpty()) {
            return;
        }

        WarehouseTRService.createCells(warehousesToCreateCells, oldMap != null);
    }

    public static void updateCellsNames(List<Warehouse__c> processingRecords, Map<Id, Warehouse__c> oldMap) {
        System.debug('WarehouseTRDispatcher => updateCellsNames');

        List<Warehouse__c> warehousesToUpdateCellsNames = new List<Warehouse__c>();

        for (Warehouse__c wh_i : processingRecords) {
            
            Warehouse__c whOld = oldMap.get(wh_i.Id);

            if (wh_i.Name != whOld.Name) {
                warehousesToUpdateCellsNames.add(wh_i);
            }
        }

        if (warehousesToUpdateCellsNames.isEmpty()) {
            return;
        }

        WarehouseTRService.updateCellsNames(warehousesToUpdateCellsNames);
    }
}