force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <description>Warehouse with parameters and capacity</description>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse__c/fields/Cells_Max_Amount__c.field-meta.xml
<CustomField>
    <fullName>Cells_Max_Amount__c</fullName>
    <formula>Height_Containers__c  *  Length_Containers__c  *  Width_Containers__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cells Max Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Height_Containers__c.field-meta.xml
<CustomField>
    <fullName>Height_Containers__c</fullName>
    <label>Height Containers</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Length_Containers__c.field-meta.xml
<CustomField>
    <fullName>Length_Containers__c</fullName>
    <label>Length Containers</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Width_Containers__c.field-meta.xml
<CustomField>
    <fullName>Width_Containers__c</fullName>
    <label>Width Containers</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/recordTypes/Warehouse.recordType-meta.xml
<RecordType>
    <fullName>Warehouse</fullName>
    <active>true</active>
    <description>Regular warehouse</description>
    <label>Warehouse</label>
</RecordType>

force-app/main/default/objects/Warehouse_Cell__c/Warehouse_Cell__c.object-meta.xml
<CustomObject>
    <label>Warehouse Cell</label>
    <nameField>
        <label>Warehouse Cell Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouse Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse_Cell__c/fields/Is_Free__c.field-meta.xml
<CustomField>
    <fullName>Is_Free__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Free</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Warehouse_Cell__c/fields/Unique_Address__c.field-meta.xml
<CustomField>
    <fullName>Unique_Address__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Unique Address</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Warehouse_Cell__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Warehouse_Cells</relationshipLabel>
    <relationshipName>Warehouse_Cells</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/WarehouseService.cls
public with sharing class WarehouseService {

    private static final List<String> LETTER_INDEX_LIST = new List<String> { 'A','B', 'C', 'D'};

    public static void specifyRelatedCells(List<Warehouse__c> warehouseList) {
        List<Warehouse_Cell__c> wCellListToInsert = new List<Warehouse_Cell__c>();
        for (Warehouse__c warehouse : warehouseList) {
            Integer wWidth = (Integer)warehouse.Width_Containers__c;
            Integer wHeight = (Integer)warehouse.Height_Containers__c;
            Integer wLenght = (Integer)warehouse.Length_Containers__c;
            for (Integer i = 0; i < warehouse.Cells_Max_Amount__c; i++) {
                String currentWidth = LETTER_INDEX_LIST[wWidth - 1];

                Warehouse_Cell__c cell = new Warehouse_Cell__c(
                    Warehouse__c = warehouse.Id, 
                    Is_Free__c = true, 
                    Unique_Address__c = currentWidth + wLenght + 'L' + wHeight
                );

                wCellListToInsert.add(cell);

                recalculateAvailableSpace(wWidth, wHeight, wHeight, warehouse);
            }
        }

        DMLExecutor.doInsert(wCellListToInsert);
    }

    public static void deleteRelatedCells(Set<Id> warehouseIdSet) {
        DMLExecutor.doDelete([SELECT Id FROM Warehouse_Cell__c WHERE Warehouse__c IN :warehouseIdSet]);
    }

    private static void recalculateAvailableSpace(Integer wWidth, Integer wHeight, Integer wLenght, Warehouse__c warehouse) {
        wWidth = wHeight - 1 > 0 && wLenght - 1 > 0 ? wWidth : wWidth - 1;
        wLenght = wHeight - 1 > 0 && wLenght - 1 > 0 ? wLenght - 1 : (Integer)warehouse.Length_Containers__c;
        wHeight = wHeight - 1 > 0 ? wHeight - 1 : (Integer)warehouse.Height_Containers__c;
    }
}